### ISSUE TITLE
invalid refresh token / access token should trigger reauthorization

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#105]
![image](https://user-images.githubusercontent.com/616885/40542071-cc7101a8-601e-11e8-95d3-7c43adc066e1.png)

showing this is not helpful to the user, better trigger the reauthorization.

By the way: a user can also revoke the application, so then the refresh token also doesn't work anymore. Also here the reauthorization should be triggered.

**Comment by fkooman** [comment]
```
Traceback (most recent call last):
  File "/home/fkooman/.local/lib/python3.6/site-packages/eduvpn/ui.py", line 87, in switched
    switched(meta=self.selected_meta, builder=self.builder)
  File "/home/fkooman/.local/lib/python3.6/site-packages/eduvpn/actions/switch.py", line 25, in switched
    activate_connection(meta=meta, builder=builder)
  File "/home/fkooman/.local/lib/python3.6/site-packages/eduvpn/actions/activate.py", line 29, in activate_connection
    config = get_profile_config(oauth, meta.api_base_uri, meta.profile_id)
  File "/home/fkooman/.local/lib/python3.6/site-packages/eduvpn/remote.py", line 261, in get_profile_config
    response = oauth.get(api_base_uri + '/profile_config?profile_id={}'.format(profile_id))
  File "/home/fkooman/.local/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/home/fkooman/.local/lib/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 343, in request
    self.auto_refresh_url, auth=auth, **kwargs
  File "/home/fkooman/.local/lib/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 309, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/home/fkooman/.local/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 411, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/home/fkooman/.local/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 379, in parse_token_response
    validate_token_parameters(params)
  File "/home/fkooman/.local/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 386, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/home/fkooman/.local/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 415, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) "refresh_token" expired
```
