### ISSUE TITLE
revoking client gives error

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#111]
![image](https://user-images.githubusercontent.com/616885/40552368-ba22eb9e-603f-11e8-902c-f921bfb511bd.png)

```
2018-05-25 17:17:19,834 - INFO - eduvpn.steps.browser - we already have a token, skipping browser step
2018-05-25 17:17:19,835 - INFO - eduvpn.steps.browser - hiding url and token dialog
2018-05-25 17:17:19,835 - INFO - eduvpn.steps.profile - fetching profile step
2018-05-25 17:17:19,846 - INFO - eduvpn.remote - Retrieving profile list from https://nl.eduvpn.org/portal/api.php
2018-05-25 17:17:20,113 - ERROR - eduvpn.util - Can't fetch profile list: request returned error 401
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fkooman/.local/lib/python3.6/site-packages/eduvpn/steps/profile.py", line 45, in <lambda>
    thread_helper(lambda: _background(oauth, meta, builder, dialog))
  File "/home/fkooman/.local/lib/python3.6/site-packages/eduvpn/steps/profile.py", line 19, in _background
    profiles = list_profiles(oauth, meta.api_base_uri)
  File "/home/fkooman/.local/lib/python3.6/site-packages/eduvpn/remote.py", line 162, in list_profiles
    raise EduvpnAuthException("request returned error 401")
eduvpn.exceptions.EduvpnAuthException: request returned error 401
```

**Comment by gijzelaerr** [comment]
for which profile is this? I'm getting into the "reauth" procedure.

**Comment by fkooman** [comment]
Yeah, you get "reauth" if all goes well. But there are some edge cases where this is not the case. E.g. when you cancel the dialog box to reauthorize.

Can't find another way at the moment to get this error except through cancel.
