### ISSUE TITLE
no error in UI when entering wrong OTP key

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#145]
There is however a backtrace: 

```
2018-07-23 11:42:43,392 - INFO - eduvpn.remote - 2fa totp enroling on https://vpn.tuxed.net/vpn-user-portal/api.php/two_factor_enroll_totp with secret=NCJSF7AYQXWPZLXA and key=543223
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fkooman/.local/lib/python3.6/site-packages/eduvpn/steps/totp_enroll.py", line 58, in <lambda>
    thread_helper(lambda: _enroll(builder, oauth, meta, config_dict, secret, key))
  File "/home/fkooman/.local/lib/python3.6/site-packages/eduvpn/steps/totp_enroll.py", line 72, in _enroll
    two_factor_enroll_totp(oauth, meta.api_base_uri, secret=secret, key=key)
  File "/home/fkooman/.local/lib/python3.6/site-packages/eduvpn/remote.py", line 362, in two_factor_enroll_totp
    raise EduvpnException(data['error'])
eduvpn.exceptions.EduvpnException: TOTP verification failed: invalid TOTP key

Traceback (most recent call last):
  File "/home/fkooman/.local/lib/python3.6/site-packages/eduvpn/steps/totp_enroll.py", line 74, in <lambda>
    GLib.idle_add(lambda: error_label.set_markup('<span color="red" size="large">{}</span>'.format(e)))
NameError: free variable 'e' referenced before assignment in enclosing scope
```

**Comment by gijzelaerr** [comment]
this is python3 only
