### ISSUE TITLE
failure while reading networkmanager configuration

### ISSUE THREAD

**Issue by baszoetekouw** [eduvpn/python-eduvpn-client#189]
# Installation

`pip install .` in virtualenv

# Version

master (85f52db00f1d64b938708638de5f1b315b9d4a6b)

# OS/Distribution

Ubuntu

# Description

Eduvpn-client crashes on start.  Apparently, one of my network-manager connections cannot be read by the current user, which the client regards as a fatal error:
```
╭╴bas@regan:~/Repositories/python-eduvpn-client [master ✔]
╰─▶ ./.venv/bin/eduvpn-client 

(eduvpn-client:28147): Gtk-WARNING **: 16:03:29.388: Theme file for Obsidian has no directories
2019-10-09 16:03:29,416 - INFO - eduvpn.steps.start - composing list of current eduVPN configurations
Traceback (most recent call last):
  File "./.venv/bin/eduvpn-client", line 10, in <module>
    sys.exit(main_eduvpn())
  File "/home/bas/Workspace/Repositories/python-eduvpn-client/.venv/lib/python3.7/site-packages/eduvpn/main.py", line 80, in main_eduvpn
    init(lets_connect=False)
  File "/home/bas/Workspace/Repositories/python-eduvpn-client/.venv/lib/python3.7/site-packages/eduvpn/main.py", line 74, in init
    edu_vpn_app.run()
  File "/home/bas/Workspace/Repositories/python-eduvpn-client/.venv/lib/python3.7/site-packages/eduvpn/ui.py", line 82, in run
    refresh_start(self.builder, self.lets_connect)
  File "/home/bas/Workspace/Repositories/python-eduvpn-client/.venv/lib/python3.7/site-packages/eduvpn/steps/start.py", line 33, in refresh_start
    providers = list(list_providers())
  File "/home/bas/Workspace/Repositories/python-eduvpn-client/.venv/lib/python3.7/site-packages/eduvpn/manager.py", line 65, in list_providers
    all_ = NetworkManager.Settings.ListConnections()  # type: ignore
  File "<string>", line 8, in ListConnections
  File "/home/bas/Workspace/Repositories/python-eduvpn-client/.venv/lib/python3.7/site-packages/eduvpn/other_nm.py", line 637, in to_python
    val = fixups.base_to_python(val)
  File "/home/bas/Workspace/Repositories/python-eduvpn-client/.venv/lib/python3.7/site-packages/eduvpn/other_nm.py", line 698, in base_to_python
    return [fixups.base_to_python(x) for x in val]
  File "/home/bas/Workspace/Repositories/python-eduvpn-client/.venv/lib/python3.7/site-packages/eduvpn/other_nm.py", line 698, in <listcomp>
    return [fixups.base_to_python(x) for x in val]
  File "/home/bas/Workspace/Repositories/python-eduvpn-client/.venv/lib/python3.7/site-packages/eduvpn/other_nm.py", line 712, in base_to_python
    return globals()[classname](val)
  File "/home/bas/Workspace/Repositories/python-eduvpn-client/.venv/lib/python3.7/site-packages/eduvpn/other_nm.py", line 327, in __init__
    self.uuid = self.GetSettings()['connection']['uuid']
  File "<string>", line 3, in GetSettings
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 147, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.NetworkManager.Settings.PermissionDenied: uid 1000 has no permission to perform this operation
```
However, my NetworkManager config is totally valid.  The network profile in question is a system-wide wifi profile that eduvpn has no business in accessing in the first place.

This issue can be easily reproduced by editing any of the profiles in `/etc/NetworkManager/system-connections` and changing the `permission=...`-line to a different user than the one that is running the eduvpn-client.

**Comment by gijzelaerr** [comment]
ouch. thanks for reporting. We will investigate asap.

**Comment by gijzelaerr** [comment]
no response from user, assuming it is resolved.

**Comment by baszoetekouw** [comment]
Sorry for the late response: the bug seems fixed, thanks!

**Comment by gijzelaerr** [comment]
no worries, thanks.
