### ISSUE TITLE
OAuth failure when trying to download a institutional profile

### ISSUE THREAD

**Issue by baszoetekouw** [eduvpn/python-eduvpn-client#190]
# Installation

`pip install .` in virtualenv

# Version

master HEAD (85f52db00f1d64b938708638de5f1b315b9d4a6b)

# OS/Distribution

Ubuntu 19.10

# Logs

╭╴bas@regan:~/Repositories/python-eduvpn-client  [master ✔]
╰─▶ ./.venv/bin/eduvpn-client

(eduvpn-client:32156): Gtk-WARNING **: 16:17:16.610: Theme file for Obsidian has no directories
2019-10-09 16:17:16,633 - INFO - eduvpn.steps.start - composing list of current eduVPN configurations
2019-10-09 16:17:16,685 - INFO - eduvpn.manager - There are 0 VPN connections innetworkmanager
2019-10-09 16:17:16,685 - INFO - eduvpn.steps.start - showing introduction
2019-10-09 16:17:20,972 - INFO - eduvpn.actions.add - add configuration clicked
2019-10-09 16:17:23,596 - INFO - eduvpn.actions.add - institute button pressed
2019-10-09 16:17:23,597 - INFO - eduvpn.steps.instance - fetching instances step
2019-10-09 16:17:23,597 - INFO - eduvpn.steps.fetching - fetching instances step
2019-10-09 16:17:23,662 - INFO - eduvpn.remote - Discovering instances at https://static.eduvpn.nl/disco/institute_access.json
2019-10-09 16:17:23,772 - INFO - eduvpn.remote - Retrieving signature https://static.eduvpn.nl/disco/institute_access.json.sig
2019-10-09 16:17:23,856 - INFO - eduvpn.remote - verifying signature of https://static.eduvpn.nl/disco/institute_access.json
2019-10-09 16:17:23,860 - INFO - eduvpn.remote - getting logo for b'Demo' from https://static.eduvpn.nl/disco/img/demo.png
2019-10-09 16:17:23,861 - INFO - eduvpn.remote - getting logo for b'G\xc3\x89ANT' from https://static.eduvpn.nl/disco/img/geant.png
2019-10-09 16:17:23,861 - INFO - eduvpn.remote - getting logo for b'EGI Foundation' from https://static.eduvpn.nl/disco/img/egi.png
2019-10-09 16:17:23,861 - INFO - eduvpn.remote - getting logo for b'Netherlands eScienceCenter' from https://static.eduvpn.nl/disco/img/nlesc.png
2019-10-09 16:17:24,028 - INFO - eduvpn.remote - getting logo for b'HEAnet' from https://static.eduvpn.nl/disco/img/heanet.png
2019-10-09 16:17:24,065 - INFO - eduvpn.remote - getting logo for b'DIFFER' from https://static.eduvpn.nl/disco/img/differ.png
2019-10-09 16:17:24,068 - INFO - eduvpn.remote - getting logo for b'Erasmus University Rotterdam' from https://static.eduvpn.nl/disco/img/eur.png
2019-10-09 16:17:24,069 - INFO - eduvpn.remote - getting logo for b'Nikhef' from https://static.eduvpn.nl/disco/img/nikhef.png
2019-10-09 16:17:24,219 - INFO - eduvpn.remote - getting logo for b'Pakistan Education & Research Network' from https://static.eduvpn.nl/disco/img/pern.png
2019-10-09 16:17:24,260 - INFO - eduvpn.remote - getting logo for b'Politechnika \xc5\x9al\xc4\x85ska' from https://static.eduvpn.nl/disco/img/polsl.png
2019-10-09 16:17:24,275 - INFO - eduvpn.remote - getting logo for b'RENATER' from https://static.eduvpn.nl/disco/img/renater.png
2019-10-09 16:17:24,277 - INFO - eduvpn.remote - getting logo for b'SURFnet' from https://static.eduvpn.nl/disco/img/surfnet.png
2019-10-09 16:17:24,418 - INFO - eduvpn.remote - getting logo for b'Perdana University' from https://static.eduvpn.nl/disco/img/perdana.png
2019-10-09 16:17:24,433 - INFO - eduvpn.remote - getting logo for b'Radboud University' from https://static.eduvpn.nl/disco/img/ru.png
2019-10-09 16:17:24,481 - INFO - eduvpn.remote - getting logo for b'STC Group' from https://static.eduvpn.nl/disco/img/stc-group.png
2019-10-09 16:17:24,487 - INFO - eduvpn.remote - getting logo for b'Tampere Universities' from https://static.eduvpn.nl/disco/img/tuni.png
2019-10-09 16:17:24,644 - INFO - eduvpn.remote - getting logo for b'Trimbos-instituut' from https://static.eduvpn.nl/disco/img/trimbos.png
2019-10-09 16:17:24,659 - INFO - eduvpn.remote - getting logo for b'Unit' from https://static.eduvpn.nl/disco/img/unit.png
2019-10-09 16:17:24,702 - INFO - eduvpn.remote - getting logo for b'Utrecht School of the Arts' from https://static.eduvpn.nl/disco/img/hku.png
2019-10-09 16:17:24,879 - INFO - eduvpn.remote - getting logo for b'University of Twente' from https://static.eduvpn.nl/disco/img/utwente.png
2019-10-09 16:17:24,904 - INFO - eduvpn.remote - getting logo for b'Uninett' from https://static.eduvpn.nl/disco/img/uninett.png
2019-10-09 16:17:25,037 - INFO - eduvpn.steps.instance - presenting instances to user
2019-10-09 16:17:32,365 - INFO - eduvpn.steps.browser - opening token dialog
2019-10-09 16:17:32,366 - INFO - eduvpn.steps.browser - starting token obtaining in background
2019-10-09 16:17:32,366 - INFO - eduvpn.remote - Retrieving info from instance https://surfnet.eduvpn.nl/
2019-10-09 16:17:32,567 - WARNING - eduvpn.remote - can't verify signature for https://surfnet.eduvpn.nl//info.json since there is no signature.
2019-10-09 16:17:32,577 - INFO - eduvpn.oauth2 - Creating an oauth session, temporarily starting webserver on port 51615 for auth callback
2019-10-09 16:17:32,578 - INFO - eduvpn.remote - Generating authorisation URL using auth endpoint https://surfnet.eduvpn.nl/portal/_oauth/authorize
2019-10-09 16:17:32,583 - INFO - eduvpn.steps.browser - opening browser with url https://surfnet.eduvpn.nl/portal/_oauth/authorize?response_type=code&client_id=org.eduvpn.app.linux&redirect_uri=http%3A%2F%2F127.0.0.1%3A51615%2Fcallback&scope=config&state=FznSQMYH9YLu4CxkAGos0HqBOkdcaF&code_challenge_method=S256&code_challenge=y3OR1KFlNlU8bjLlWobuMEoR03rPHG9-o8uMwAHYqAo
2019-10-09 16:17:32,843 - INFO - eduvpn.oauth2 - waiting for callback on port 51615
2019-10-09 16:17:32,843 - INFO - eduvpn.oauth2 - listening for a request on port 51615...
127.0.0.1 - - [09/Oct/2019 16:17:39] "GET /callback?code=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsImtpZCI6Im5MeTBYdGpQenB3V1djNE9mMV9hOU1qTDc3TTdUUTZRVl9HdkRrM243SjAifQ.eyJ2Ijo1LCJ0eXBlIjoiYXV0aG9yaXphdGlvbl9jb2RlIiwiYXV0aF9rZXkiOiJhMWFjZWQ2MjJjOGY4NDc4MzhlYjgyMTU2M2UwNjI1NyIsInVzZXJfaWQiOiJodHRwczpcL1wvc2EtZ3cuc3VyZmNvbmV4dC5ubFwvYXV0aGVudGljYXRpb25cL21ldGFkYXRhIWh0dHBzOlwvXC9zdXJmbmV0LmVkdXZwbi5ubFwvc2FtbCEyNjQxYjhiZTgxMzczMDc0OWU0ZDljM2MxZDZmZGZlNjEzMGY5ZWRhIiwiY2xpZW50X2lkIjoib3JnLmVkdXZwbi5hcHAubGludXgiLCJzY29wZSI6ImNvbmZpZyIsInJlZGlyZWN0X3VyaSI6Imh0dHA6XC9cLzEyNy4wLjAuMTo1MTYxNVwvY2FsbGJhY2siLCJjb2RlX2NoYWxsZW5nZSI6InkzT1IxS0ZsTmxVOGJqTGxXb2J1TUVvUjAzclBIRzktbzh1TXdBSFlxQW8iLCJleHBpcmVzX2F0IjoiMjAxOS0xMC0wOVQxNDoyMjozOSswMDowMCJ9.PYPUEkH8HxSAH6xvWiT31wM8k0-kJzdteCIsUskE3pGxPxqvG-RXufddxnY3dB5WWPnC3Ym4vC42LxzL8SmDAQ&state=FznSQMYH9YLu4CxkAGos0HqBOkdcaF HTTP/1.1" 200 -
2019-10-09 16:17:39,451 - INFO - eduvpn.oauth2 - received a request /callback?code=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsImtpZCI6Im5MeTBYdGpQenB3V1djNE9mMV9hOU1qTDc3TTdUUTZRVl9HdkRrM243SjAifQ.eyJ2Ijo1LCJ0eXBlIjoiYXV0aG9yaXphdGlvbl9jb2RlIiwiYXV0aF9rZXkiOiJhMWFjZWQ2MjJjOGY4NDc4MzhlYjgyMTU2M2UwNjI1NyIsInVzZXJfaWQiOiJodHRwczpcL1wvc2EtZ3cuc3VyZmNvbmV4dC5ubFwvYXV0aGVudGljYXRpb25cL21ldGFkYXRhIWh0dHBzOlwvXC9zdXJmbmV0LmVkdXZwbi5ubFwvc2FtbCEyNjQxYjhiZTgxMzczMDc0OWU0ZDljM2MxZDZmZGZlNjEzMGY5ZWRhIiwiY2xpZW50X2lkIjoib3JnLmVkdXZwbi5hcHAubGludXgiLCJzY29wZSI6ImNvbmZpZyIsInJlZGlyZWN0X3VyaSI6Imh0dHA6XC9cLzEyNy4wLjAuMTo1MTYxNVwvY2FsbGJhY2siLCJjb2RlX2NoYWxsZW5nZSI6InkzT1IxS0ZsTmxVOGJqTGxXb2J1TUVvUjAzclBIRzktbzh1TXdBSFlxQW8iLCJleHBpcmVzX2F0IjoiMjAxOS0xMC0wOVQxNDoyMjozOSswMDowMCJ9.PYPUEkH8HxSAH6xvWiT31wM8k0-kJzdteCIsUskE3pGxPxqvG-RXufddxnY3dB5WWPnC3Ym4vC42LxzL8SmDAQ&state=FznSQMYH9YLu4CxkAGos0HqBOkdcaF
2019-10-09 16:17:39,452 - INFO - eduvpn.steps.browser - control returned by browser
2019-10-09 16:17:39,452 - INFO - eduvpn.steps.browser - setting oauth token for metadata
2019-10-09 16:17:39,616 - ERROR - eduvpn.util - Can't obtain token: (invalid_request) missing "client_id" parameter
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bas/Workspace/Repositories/python-eduvpn-client/.venv/lib/python3.7/site-packages/eduvpn/steps/browser.py", line 81, in <lambda>
    lets_connect=lets_connect))
  File "/home/bas/Workspace/Repositories/python-eduvpn-client/.venv/lib/python3.7/site-packages/eduvpn/steps/browser.py", line 125, in _phase2_background
    code_verifier=code_verifier)
  File "/home/bas/Workspace/Repositories/python-eduvpn-client/.venv/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 307, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/home/bas/Workspace/Repositories/python-eduvpn-client/.venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/home/bas/Workspace/Repositories/python-eduvpn-client/.venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "/home/bas/Workspace/Repositories/python-eduvpn-client/.venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 438, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/home/bas/Workspace/Repositories/python-eduvpn-client/.venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) missing "client_id" parameter
```

## Do you have a problem while adding a profile?

I click add, choose "institutional access", select my IdP, log in in the browser, allow access for eduVPN, then receive the error "(invalid_request) missing `client_id" parameter`.

**Comment by gijzelaerr** [comment]
hi! Thanks, for reporting. This is a known issue with the current master. We are working on it! For now, we recommend using the latest release.

**Comment by gijzelaerr** [comment]
should be addressed by https://github.com/eduvpn/python-eduvpn-client/pull/193

**Comment by kingabhijit01** [comment]
Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 150, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

**Comment by gijzelaerr** [comment]
This seems to have nothing to do with python-eduvpn-client.
