### ISSUE TITLE
Unicode providers don't work with python2

### ISSUE THREAD

**Issue by maxadamo** [eduvpn/python-eduvpn-client#191]
# Installation

Debian repository

# Version

eduvpn-client  1.0.2-1

# OS/Distribution

Ubuntu 19.04

# Logs

## Do you have a problem while adding a profile?

NO

## Do you have a problem during connecting? 

NO

## Issue

I was able to stat eduvpn-client only once. From the second time, it always tries to load the system connection from my home directory. But system connection are stored elsewhere (under `/etc/NetworkManager/system-connections/`), hence it does not find the files and throws the error below: 

```
 $  eduvpn-client -d
2019-10-22 16:58:35,535 - DEBUG - eduvpn.main - using production discovery URLs
2019-10-22 16:58:35,596 - DEBUG - eduvpn.util - looking for 'share/eduvpn/builder/window.ui' in '/usr/lib/python2.7/dist-packages'
2019-10-22 16:58:35,596 - DEBUG - eduvpn.util - looking for 'share/eduvpn/builder/window.ui' in '/home/maxadamo/.local'
2019-10-22 16:58:35,596 - DEBUG - eduvpn.util - looking for 'share/eduvpn/builder/window.ui' in '/usr/local'
2019-10-22 16:58:35,596 - DEBUG - eduvpn.util - looking for 'share/eduvpn/builder/window.ui' in '/usr'
2019-10-22 16:58:35,872 - INFO - eduvpn.steps.start - composing list of current eduVPN configurations
2019-10-22 16:58:36,022 - INFO - eduvpn.manager - There are 4 VPN connections in networkmanager
2019-10-22 16:58:36,022 - ERROR - eduvpn.metadata - can't open metdata file for 73f94958-058b-4c92-9c52-f6551bfdda04: [Errno 2] No such file or directory: u'/home/maxadamo/.config/eduvpn/73f94958-058b-4c92-9c52-f6551bfdda04.json'
2019-10-22 16:58:36,023 - ERROR - eduvpn.metadata - can't open metdata file for 3337069b-128a-4cd6-8c84-7ef7f885c5f2: [Errno 2] No such file or directory: u'/home/maxadamo/.config/eduvpn/3337069b-128a-4cd6-8c84-7ef7f885c5f2.json'
2019-10-22 16:58:36,023 - ERROR - eduvpn.metadata - can't open metdata file for 120c3889-37fe-4167-924e-e1dbe6116e29: [Errno 2] No such file or directory: u'/home/maxadamo/.config/eduvpn/120c3889-37fe-4167-924e-e1dbe6116e29.json'
2019-10-22 16:58:36,023 - INFO - eduvpn.steps.start - hiding introduction
Traceback (most recent call last):
  File "/usr/bin/eduvpn-client", line 11, in <module>
    load_entry_point('eduvpn-client==1.0.2', 'gui_scripts', 'eduvpn-client')()
  File "/usr/lib/python2.7/dist-packages/eduvpn/main.py", line 82, in main_eduvpn
    init(lets_connect=False)
  File "/usr/lib/python2.7/dist-packages/eduvpn/main.py", line 77, in init
    edu_vpn_app.run()
  File "/usr/lib/python2.7/dist-packages/eduvpn/ui.py", line 76, in run
    refresh_start(self.builder, self.lets_connect)
  File "/usr/lib/python2.7/dist-packages/eduvpn/steps/start.py", line 36, in refresh_start
    connection_type = "<b>{}</b>\n{}\n<small><i>{}</i></small>".format(meta.display_name, meta.connection_type, meta.profile_display_name)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc9' in position 1: ordinal not in range(128)
```

**Comment by gijzelaerr** [comment]
hi! There is addition information stored in `~/.config/eduvpn`. I'm not sure why the metdata can't be found, but it seems that something going wrong related to unicode. What eduvpn configurations do you have in network manager? Do any of the profiles contain non-ASCII characters?

**Comment by gijzelaerr** [comment]
Please verify if PR https://github.com/eduvpn/python-eduvpn-client/pull/196 fixes your issue.

**Comment by maxadamo** [comment]
it works!

**Comment by gijzelaerr** [comment]
thanks. this issue seems to be resolved.
