### ISSUE TITLE
can't finalize configuration: ValueError: Missing access token.

### ISSUE THREAD

**Issue by hurngchunlee** [eduvpn/python-eduvpn-client#198]
# Installation

How did you install the eduVPN client?

```bash
sudo pip install git+https://github.com/eduvpn/python-eduvpn-client.git
```
# Version

What version of the client you are running? Try your package manager or otherwise `$ eduvpn-client -v`.

```bash
$ eduvpn-client -v
eduVPN Linux client version 0.0dev
```
# OS/Distribution

What operating system/distribution and version you are running?

Arch Linux w/ kernel 4.19.88-1-lts

# Logs

```
2019-12-14 10:11:02,887 - INFO - eduvpn.steps.start - composing list of current eduVPN configurations
2019-12-14 10:11:02,916 - INFO - eduvpn.manager - There are 1 VPN connections innetworkmanager
2019-12-14 10:11:02,916 - INFO - eduvpn.steps.start - hiding introduction
2019-12-14 10:11:04,615 - INFO - eduvpn.actions.select - configuration was selected Radboud University (f9953c77-0861-4845-b588-6dc2f6f44366)
2019-12-14 10:11:04,618 - INFO - eduvpn.manager - getting list of active connections
2019-12-14 10:11:04,630 - INFO - eduvpn.steps.messages - fetching user and system messages from Radboud University (https://ru.eduvpn.nl/portal/api.php)
2019-12-14 10:11:04,630 - INFO - eduvpn.remote - Retrieving user messages from https://ru.eduvpn.nl/portal/api.php
2019-12-14 10:11:04,718 - INFO - eduvpn.steps.reauth - looks like authorization is expired or removed
2019-12-14 10:11:06,423 - INFO - eduvpn.steps.browser - opening token dialog
2019-12-14 10:11:06,423 - INFO - eduvpn.steps.browser - starting token obtaining in background
2019-12-14 10:11:06,424 - INFO - eduvpn.remote - Retrieving info from instance https://ru.eduvpn.nl/
2019-12-14 10:11:06,572 - WARNING - eduvpn.remote - can't verify signature for https://ru.eduvpn.nl//info.json since there is no signature.
token: {None: None}
2019-12-14 10:11:06,574 - INFO - eduvpn.steps.browser - we already have a token, skipping browser step
2019-12-14 10:11:06,574 - INFO - eduvpn.steps.browser - hiding url and token dialog
2019-12-14 10:11:06,575 - INFO - eduvpn.steps.profile - fetching profile step
2019-12-14 10:11:06,575 - INFO - eduvpn.steps.profile - we already selected the profile in the past, not presenting user with choice again
2019-12-14 10:11:06,575 - INFO - eduvpn.steps.parse_config - parse config step
2019-12-14 10:11:06,575 - INFO - eduvpn.steps.fetching - fetching instances step
2019-12-14 10:11:06,630 - INFO - eduvpn.remote - Creating and retrieving key pair from https://ru.eduvpn.nl/portal/api.php
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/eduvpn/steps/parse_config.py", line 22, in <lambda>
    thread_helper(lambda: _background(meta=meta, oauth=oauth, dialog=dialog, builder=builder,
  File "/usr/lib/python3.8/site-packages/eduvpn/steps/parse_config.py", line 31, in _background
    cert, key = create_keypair(oauth, meta.api_base_uri)
  File "/usr/lib/python3.8/site-packages/eduvpn/remote.py", line 136, in create_keypair
    response = oauth.post(api_base_uri + '/create_keypair', data={'display_name': 'eduVPN for Linux'})
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 477, in request
    url, headers, data = self._client.add_token(
  File "/usr/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 195, in add_token
    raise ValueError("Missing access token.")
ValueError: Missing access token.
2019-12-14 10:11:06,642 - ERROR - eduvpn.util - can't finalize configuration: ValueError: Missing access token.
```

## Do you have a problem while adding a profile?

No, everything works fine at the time adding  a new profile.  The problem happens when the access token of the existing profile is expired.  However, the eduvpn-client skips the step to open the browser for renewing the token via IdP authentication. 

I traced a bit the code, and noticed that the following line in `eduvpn/steps/browser.py` prevents the token renewal and therefore causing the missing token error in the end.

https://github.com/eduvpn/python-eduvpn-client/blob/2bead84be087341c95d58c90224654e233f0e288/eduvpn/steps/browser.py#L56

After I changed the line to

```python
if not meta.token or meta.token == {None: None}:
```
It works again.

## Do you have a problem during connecting?

No

**Comment by gijzelaerr** [comment]
interesting, thanks for the detailed report. will investivate.

**Comment by gijzelaerr** [comment]
hi @hurngchunlee ! can you see if this PR fixes your issue?

https://github.com/eduvpn/python-eduvpn-client/pull/201

**Comment by hurngchunlee** [comment]
Hi @gijzelaerr,

Yes, it works!  Thanks for the fix.

**Comment by gijzelaerr** [comment]
ok perfect, thanks for testing!
