### ISSUE TITLE
ERROR - eduvpn.util - Can't check account status: org.freedesktop.NetworkManager.UnknownConnection: Could not find source connection.

### ISSUE THREAD

**Issue by amarsman** [eduvpn/python-eduvpn-client#226]
Error occurred when a previously created connection was enabled. 

# Installation

How did you install the eduVPN client?

make run

# Version

What version of the client you are running? Try your package manager or otherwise `$ eduvpn-client -v`.

Tag 1.1

# OS/Distribution

What operating system/distribution and version you are running?

Debian GNU/Linux 10 (buster)

# Logs

## Do you have a problem while adding a profile?

Eduvpn will print out information to the console while running. Please try running `eduvpn-client` in a console.  Are there any interesting logs appearing when you try to connect? There is also a more verbose mode available which is enabled with the `-d` flag.

2020-04-28 10:59:54,430 - INFO - eduvpn.manager - connecting profile with uuid ... NetworkManager
2020-04-28 10:59:54,434 - ERROR - eduvpn.util - Can't check account status: org.freedesktop.NetworkManager.UnknownConnection: Could not find source connection.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/eduvpn/manager.py", line 161, in connect_provider
    return NetworkManager.NetworkManager.ActivateConnection(connection, "/", "/")  # type: ignore
  File "<string>", line 6, in ActivateConnection
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.NetworkManager.UnknownConnection: Could not find source connection.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/eduvpn/actions/activate.py", line 42, in <lambda>
    thread_helper(lambda: _auth_check(oauth, meta, verifier, builder, lets_connect=lets_connect))
  File "/usr/lib/python3/dist-packages/eduvpn/actions/activate.py", line 57, in _auth_check
    _cert_check(meta, oauth, builder, info, lets_connect)
  File "/usr/lib/python3/dist-packages/eduvpn/actions/activate.py", line 84, in _cert_check
    _fetch_updated_config(oauth, meta, builder, info, lets_connect)
  File "/usr/lib/python3/dist-packages/eduvpn/actions/activate.py", line 95, in _fetch_updated_config
    _2fa_check(meta, builder, oauth, config_dict, info, lets_connect)
  File "/usr/lib/python3/dist-packages/eduvpn/actions/activate.py", line 105, in _2fa_check
    connect_provider(meta.uuid)
  File "/usr/lib/python3/dist-packages/eduvpn/manager.py", line 163, in connect_provider
    raise EduvpnException(e)
eduvpn.exceptions.EduvpnException: org.freedesktop.NetworkManager.UnknownConnection: Could not find source connection.

## Do you have a problem during connecting?

Please examine the eduvpn for errors or messages while connecting. Note that the actual VPN connection management is not done by eduVPN, but by network management tool bundeled with your OS named networkManager. You can examine the NetworkManager logs with `$ sudo journalctl -u NetworkManager`.

Apr 28 10:59:54 einstein NetworkManager[16603]: <info>  [1588064394.4296] settings-connection[0x5592dad0cb80,8c5da05a-e5c5-4c0f-b567-de86a1fbdbbc]: write: successfully updated (keyfile: update /etc/NetworkManager/system-connections/Demo.nmconnection (8c5da05a-e5c5-4c0f-b567-de86a1fbdbbc,"Demo"))
Apr 28 10:59:54 einstein NetworkManager[16603]: <info>  [1588064394.4303] audit: op="connection-update" uuid="8c5da05a-e5c5-4c0f-b567-de86a1fbdbbc" name="Demo" args="vpn.data" pid=6647 uid=1000 result="success"
Apr 28 10:59:54 einstein NetworkManager[16603]: <info>  [1588064394.4338] audit: op="connection-activate" uuid="8c5da05a-e5c5-4c0f-b567-de86a1fbdbbc" name="Demo" pid=6647 uid=1000 result="fail" reason="Could not find source connection."

**Comment by gijzelaerr** [comment]
This is a race condition in the old dbus logic. Since we are completely going to rewrite this code I think this issue will not occur anymore.

**Comment by gijzelaerr** [comment]
I'm going to close this issue since we are most likely not going to look into this anymore.
