### ISSUE TITLE
building eduVPN from fc31.src.rpm on Fedora 32 fails

### ISSUE THREAD

**Issue by cunio** [eduvpn/python-eduvpn-client#237]
# Installation

rpmbuild --rebuild eduvpn_client-1.1-1.fc31.src.rpm

# Version
1.1-1

# OS/Distribution
Fedora 32

# Logs
======================================================================
ERROR: test_switched_on (tests.actions.test_switch.TestActions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/mock.py", line 1325, in patched
    return func(*newargs, **newkeywargs)
  File "/run/media/jacek/home/jacek/rpmbuild/BUILD/eduvpn_client-1.1/tests/actions/test_switch.py", line 49, in test_switched_on
    switched(builder=self.builder, meta=self.meta, verifier=self.verifier, lets_connect=False)
  File "/run/media/jacek/home/jacek/rpmbuild/BUILD/eduvpn_client-1.1/eduvpn/actions/switch.py", line 31, in switched
    notify(notification, u"eduVPN disconnecting...", u"Disconnecting from {}".format(meta.display_name))
  File "/run/media/jacek/home/jacek/rpmbuild/BUILD/eduvpn_client-1.1/eduvpn/notify.py", line 33, in notify
    notification.show()
gi.repository.GLib.GError: g-io-error-quark: GDBus.Error:org.freedesktop.Notifications.Error.ExcessNotificationGeneration: Created too many similar notifications in quick succession (36)

**Comment by gijzelaerr** [comment]
We are working towards a 2.0 release which has an improved unit test suite, this will probably not happen again.

**Comment by gijzelaerr** [comment]
this should be resolved in 2.0
