### ISSUE TITLE
Error with cli when nm and/or dbus are not installed or not available

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#260]
This is since pygobject is not installed by default, we should check on that.

```
> 0
Traceback (most recent call last):
  File "venv/bin/eduvpn-client", line 11, in <module>
    load_entry_point('eduvpn-client', 'console_scripts', 'eduvpn-client')()
  File "/Users/gijs/Work/tmp/venv/src/eduvpn/eduvpn/__main__.py", line 78, in eduvpn
    parse_eduvpn(argv[1:])
  File "/Users/gijs/Work/tmp/venv/src/eduvpn/eduvpn/__main__.py", line 41, in parse_eduvpn
    parsed.func(parsed)
  File "/Users/gijs/Work/tmp/venv/src/eduvpn/eduvpn/cli.py", line 112, in interactive
    start(auth_url, secure_internet=secure_internets, interactive=True)
  File "/Users/gijs/Work/tmp/venv/src/eduvpn/eduvpn/cli.py", line 188, in start
    client = get_client()
  File "/Users/gijs/Work/tmp/venv/src/eduvpn/eduvpn/nm.py", line 29, in get_client
    return NM.Client.new(None)
AttributeError: 'NoneType' object has no attribute 'Client'
```

**Comment by gijzelaerr** [comment]
should be fixed in https://github.com/eduvpn/python-eduvpn-client/pull/289

**Comment by gijzelaerr** [comment]
this has been resolved.
