### ISSUE TITLE
TypeError: write() argument must be str, not None

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#265]
This came by in the console:

```
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gijs/Work/python-eduvpn-client/eduvpn/ui/ui.py", line 546, in <lambda>
    thread_helper(lambda: finalize_configuration_thread(profile_id, self))
  File "/home/gijs/Work/python-eduvpn-client/eduvpn/ui/ui.py", line 622, in finalize_configuration_thread
    set_api_url(gui.data.api_url)
  File "/home/gijs/Work/python-eduvpn-client/eduvpn/storage.py", line 126, in set_api_url
    return _set_setting("api_url", api_url)
  File "/home/gijs/Work/python-eduvpn-client/eduvpn/storage.py", line 53, in _set_setting
    f.write(value)
TypeError: write() argument must be str, not None
```

**Comment by amarsman** [comment]
This is caused by the back button which is already enabled while a new connection is being created and saved.
