### ISSUE TITLE
Debian: connecting to another vpn server fails

### ISSUE THREAD

**Issue by amarsman** [eduvpn/python-eduvpn-client#269]
eduvpn.nm - nm.py:122 - Updating existing connection with new configuration
```
Traceback (most recent call last):
  File "/media/psf/Home/projects/eduvpn/python-eduvpn-client/fork/git-python-eduvpn-client-fork/eduvpn/nm.py", line 112, in update_connection_callback
    res = remote_connection.commit_changes_finish(result)
gi.repository.GLib.Error: nm-settings-error-quark: connection eduVPN cannot change the UUID from 85cd82c3-797b-47dd-a023-2ad6cd183535 to b3636890-2e31-4647-b8bd-3cfcce5c63e3 (0)
```

**Comment by amarsman** [comment]
Debian 10: network-manager  1.14.6-2 and network-manager-openvpn 1.8.10-1

Ubuntu 20.04: network-manager 1.22.10-1 and network-manager-openvpn 1.8.12-1

**Comment by amarsman** [comment]
To reproduce:

Start with a clean config: rm -rf ~/.config/eduvpn

venv/bin/eduvpn-gui -d

Select demo, select profile, connection will automagicallly start.

Stop connection using the switch

Go back

Select Demo again

2021-02-05 15:32:16,055 - DEBUG - requests_oauthlib.oauth2_session - oauth2_session.py:358 - Passing through key word arguments {'json': None}.
2021-02-05 15:32:17,522 - DEBUG - urllib3.connectionpool - connectionpool.py:393 - https://demo.eduvpn.nl:443 "POST /portal/api.php/create_keypair HTTP/1.1" 200 None
2021-02-05 15:32:17,527 - DEBUG - eduvpn.ui.ui - ui.py:881 - configuration_finalized
2021-02-05 15:32:17,527 - INFO - eduvpn.ui.ui - ui.py:896 - nm available:
2021-02-05 15:32:17,528 - INFO - eduvpn.nm - nm.py:114 - writing configuration to Network Manager
2021-02-05 15:32:17,528 - INFO - eduvpn.storage - storage.py:162 - Writing configuration to /tmp/tmpg5olaira/eduVPN.ovpn
2021-02-05 15:32:17,534 - INFO - eduvpn.nm - nm.py:106 - Updating existing connection with new configuration
Traceback (most recent call last):
  File "/media/psf/Home/projects/eduvpn/python-eduvpn-client/fork/debian-fresh/python-eduvpn-client/eduvpn/nm.py", line 96, in update_connection_callback
    res = remote_connection.commit_changes_finish(result)
gi.repository.GLib.Error: nm-settings-error-quark: connection eduVPN cannot change the UUID from 8a556476-3543-4811-aae6-0f7bf0d42fae to e2faa6b3-2c09-4ff8-ac01-dbbbec3a9e5d (0)

This works fine on e.g. Ubuntu and Fedora.

**Comment by amarsman** [comment]
Tested on Debian 10.9 with the master version (94a3221c1de361a07e73f1fd33144dbba946b19c). 

2021-03-28 13:39:25,850 - MainThread - INFO - eduvpn.nm - nm.py:129 - writing configuration to Network Manager
2021-03-28 13:39:25,852 - MainThread - INFO - eduvpn.storage - storage.py:162 - Writing configuration to /tmp/tmpjiky0rna/eduVPN.ovpn
2021-03-28 13:39:25,862 - MainThread - INFO - eduvpn.nm - nm.py:121 - Updating existing connection with new configuration
Traceback (most recent call last):
  File "/media/psf/Home/projects/eduvpn/python-eduvpn-client/upstream/eduvpn/nm.py", line 111, in update_connection_callback
    res = remote_connection.commit_changes_finish(result)
gi.repository.GLib.Error: nm-settings-error-quark: connection eduVPN cannot change the UUID from e4b4895d-ab19-4874-a509-07e127a176d4 to f7b4b32d-7a36-422f-ace2-2fa8e1057622 (0)

Configuring screen is shown forever without a possibility to go back.

![image](https://user-images.githubusercontent.com/14363168/112750959-a38d1f80-8fcb-11eb-86c8-097b4a886773.png)

**Comment by amarsman** [comment]
Also got a segmentation fault while reproducing this issue:

$ venv/bin/eduvpn-gui -d
2021-03-28 13:38:33,629 - MainThread - DEBUG - /media/psf/Home/projects/eduvpn/python-eduvpn-client/upstream/eduvpn/utils.py - utils.py:28 - looking for 'share/eduvpn/builder/mainwindow.ui' in '/media/psf/Home/projects/eduvpn/python-eduvpn-client/upstream'

(eduvpn-gui:3205): Gtk-WARNING **: 13:38:33.847: Overriding tab label for notebook

(eduvpn-gui:3205): Gtk-WARNING **: 13:38:33.850: Overriding tab label for notebook
2021-03-28 13:38:33,854 - MainThread - INFO - eduvpn.ui.ui - ui.py:121 - starting ui
2021-03-28 13:38:33,861 - init-server-db - INFO - eduvpn.remote - remote.py:23 - Requesting https://disco.eduvpn.org/v2/server_list.json
2021-03-28 13:38:33,863 - init-server-db - DEBUG - urllib3.connectionpool - connectionpool.py:815 - Starting new HTTPS connection (1): disco.eduvpn.org:443
Segmentation fault

**Comment by alvra** [comment]
The linked PR #350 fixes the first issue: "connection eduVPN cannot change the UUID".
The segfault seems to be a separate issue. @amarsman can you create a new issue with details on how to reproduce this?

**Comment by amarsman** [comment]
See my remarks on the PR for the first issue. I didn't see the sigseg during my testing today, will create a PR when I see it again as I don't have a way to reproduce always. I started clean back then and added/removed/re-added Demo.

**Comment by gijzelaerr** [comment]
i guess this is resolved now, please reopen if this reoccurs
