### ISSUE TITLE
eduVPN 2.0 package should depend on gir1.2-nm-1.0

### ISSUE THREAD

**Issue by mrvanes** [eduvpn/python-eduvpn-client#358]
# Installation
Debian packages

# Version
2.0.0-1

# OS/Distribution
Ubuntu 21.04

# Logs
```
$ eduvpn-gui 
2021-04-19 07:44:31,566 - MainThread - ERROR - eduvpn.ui.__main__ - __main__.py:77 - Caught exception: Namespace NM not available
2021-04-19 07:44:31,566 - MainThread - ERROR - root - __main__.py:78 - Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/eduvpn/ui/__main__.py", line 71, in main_loop
    from eduvpn.ui.ui import EduVpnGui
  File "/usr/lib/python3/dist-packages/eduvpn/ui/ui.py", line 15, in <module>
    gi.require_version('NM', '1.0')  # noqa: E402
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace NM not available
```

# Solution
```apt install gir1.2-nm-1.0```

This should be a dependancy when installing 2.0.

**Comment by gijzelaerr** [comment]
correct! sorry about that. will try to fix that on friday.

**Comment by gijzelaerr** [comment]
@mrvanes to make sure this is ready for the 2.1 release I pushed a 2.0.0-2 package that includes this fix.

@mrvanes can you check if this problem solves your issue?

**Comment by mrvanes** [comment]
I can't test if this solves the problem since I already have a working system, but I can see that python3-eduvpn-client would have installed gir1.2-nm-1.0 now so I assume it's fixed. Thx!
