### ISSUE TITLE
Search for institutions doesn't work

### ISSUE THREAD

**Issue by arusf2011** [eduvpn/python-eduvpn-client#372]
Hello everyone.

### Issue description
When I tried to search for my institution with `eduvpn-cli` I got this error:
```
$ eduvpn-cli search name_of_institution
INFO:eduvpn.remote:Requesting https://disco.eduvpn.org/v2/server_list.json
INFO:eduvpn.remote:Retrieving signature https://disco.eduvpn.org/v2/server_list.json.minisig
INFO:eduvpn.remote:verifying signature of https://disco.eduvpn.org/v2/server_list.json
ERROR:eduvpn.remote:Got exception 'VerifyKey' object has no attribute '__unicode__' requesting https://disco.eduvpn.org/v2/server_list.json for server_list
Traceback (most recent call last):
  File "/usr/bin/eduvpn-cli", line 11, in <module>
    load_entry_point('eduvpn-client==2.0.0', 'console_scripts', 'eduvpn-cli')()
  File "/usr/lib/python3/dist-packages/eduvpn/cli.py", line 139, in eduvpn
    parse_eduvpn(argv[1:])
  File "/usr/lib/python3/dist-packages/eduvpn/cli.py", line 105, in parse_eduvpn
    parsed.func(parsed)
  File "/usr/lib/python3/dist-packages/eduvpn/cli.py", line 22, in search
    menu.search(args)
  File "/usr/lib/python3/dist-packages/eduvpn/menu.py", line 122, in search
    servers, orgs = fetch_servers_orgs()
  File "/usr/lib/python3/dist-packages/eduvpn/menu.py", line 20, in fetch_servers_orgs
    servers = list_servers(SERVER_URI)
  File "/usr/lib/python3/dist-packages/eduvpn/remote.py", line 74, in list_servers
    result = request(uri, verify=True)['server_list']
  File "/usr/lib/python3/dist-packages/eduvpn/remote.py", line 46, in request
    _ = validate(content=response.content, signature=signature)
  File "/usr/lib/python3/dist-packages/eduvpn/crypto.py", line 94, in validate
    logger.debug(f"Used signature {f}")
  File "/usr/lib/python3/dist-packages/nacl/utils.py", line 54, in __str__
    return self.__unicode__()
AttributeError: 'VerifyKey' object has no attribute '__unicode__' 
```
Same error appears in `eduvpn-gui` on launch.
After complete launch search doesn't show any result,
Log for `eduvpn-gui`:
```
$ eduvpn-gui
2021-05-09 10:58:37,002 - MainThread - INFO - eduvpn.ui.ui - ui.py:133 - i18n successfully initialized

(eduvpn-gui:3352): Gtk-WARNING **: 10:58:37.191: Overriding tab label for notebook

(eduvpn-gui:3352): Gtk-WARNING **: 10:58:37.194: Overriding tab label for notebook
2021-05-09 10:58:37,208 - MainThread - INFO - eduvpn.ui.ui - ui.py:172 - starting ui
2021-05-09 10:58:37,230 - MainThread - INFO - eduvpn.app - app.py:111 - network transitioning: <InitialNetworkState> -> no_previous_connection_found
2021-05-09 10:58:37,231 - MainThread - INFO - eduvpn.app - app.py:130 - interface transitioning: <InitialInterfaceState> -> no_active_connection_found
2021-05-09 10:58:37,239 - MainThread - INFO - eduvpn.app - app.py:141 - interface transitioned: no_active_connection_found -> <ConfigurePredefinedServer search_query='' results=None>
2021-05-09 10:58:37,240 - MainThread - INFO - eduvpn.app - app.py:122 - network transitioned: no_previous_connection_found -> <UnconnectedState>
2021-05-09 10:58:37,245 - init-server-db - INFO - eduvpn.remote - remote.py:23 - Requesting https://disco.eduvpn.org/v2/server_list.json
2021-05-09 10:58:37,692 - init-server-db - INFO - eduvpn.remote - remote.py:37 - Retrieving signature https://disco.eduvpn.org/v2/server_list.json.minisig
2021-05-09 10:58:37,981 - init-server-db - INFO - eduvpn.remote - remote.py:44 - verifying signature of https://disco.eduvpn.org/v2/server_list.json
2021-05-09 10:58:37,983 - init-server-db - ERROR - eduvpn.remote - remote.py:76 - Got exception 'VerifyKey' object has no attribute '__unicode__' requesting https://disco.eduvpn.org/v2/server_list.json for server_list
Exception in thread init-server-db:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/eduvpn/app.py", line 77, in initialize_server_db
    self.server_db.update()
  File "/usr/lib/python3/dist-packages/eduvpn/server.py", line 244, in update
    server_list = remote.list_servers(SERVER_URI)
  File "/usr/lib/python3/dist-packages/eduvpn/remote.py", line 74, in list_servers
    result = request(uri, verify=True)['server_list']
  File "/usr/lib/python3/dist-packages/eduvpn/remote.py", line 46, in request
    _ = validate(content=response.content, signature=signature)
  File "/usr/lib/python3/dist-packages/eduvpn/crypto.py", line 94, in validate
    logger.debug(f"Used signature {f}")
  File "/usr/lib/python3/dist-packages/nacl/utils.py", line 54, in __str__
    return self.__unicode__()
AttributeError: 'VerifyKey' object has no attribute '__unicode__'

2021-05-09 10:58:56,040 - MainThread - INFO - eduvpn.app - app.py:130 - interface transitioning: <ConfigurePredefinedServer search_query='' results=None> -> enter_search_query
2021-05-09 10:58:56,044 - MainThread - INFO - eduvpn.app - app.py:141 - interface transitioned: enter_search_query -> <PendingConfigurePredefinedServer search_query='P'>
2021-05-09 10:58:56,204 - MainThread - INFO - eduvpn.app - app.py:130 - interface transitioning: <PendingConfigurePredefinedServer search_query='P'> -> enter_search_query
2021-05-09 10:58:56,205 - MainThread - INFO - eduvpn.app - app.py:141 - interface transitioned: enter_search_query -> <PendingConfigurePredefinedServer search_query='Po'>
2021-05-09 10:58:56,403 - MainThread - INFO - eduvpn.app - app.py:130 - interface transitioning: <PendingConfigurePredefinedServer search_query='Po'> -> enter_search_query
2021-05-09 10:58:56,404 - MainThread - INFO - eduvpn.app - app.py:141 - interface transitioned: enter_search_query -> <PendingConfigurePredefinedServer search_query='Pol'>
2021-05-09 10:58:56,804 - MainThread - INFO - eduvpn.app - app.py:130 - interface transitioning: <PendingConfigurePredefinedServer search_query='Pol'> -> enter_search_query
2021-05-09 10:58:56,805 - MainThread - INFO - eduvpn.app - app.py:141 - interface transitioned: enter_search_query -> <PendingConfigurePredefinedServer search_query='Polite'>
2021-05-09 10:58:57,121 - MainThread - INFO - eduvpn.app - app.py:130 - interface transitioning: <PendingConfigurePredefinedServer search_query='Polite'> -> enter_search_query
2021-05-09 10:58:57,122 - MainThread - INFO - eduvpn.app - app.py:141 - interface transitioned: enter_search_query -> <PendingConfigurePredefinedServer search_query='Politech'>
2021-05-09 10:58:57,310 - MainThread - INFO - eduvpn.app - app.py:130 - interface transitioning: <PendingConfigurePredefinedServer search_query='Politech'> -> enter_search_query
2021-05-09 10:58:57,311 - MainThread - INFO - eduvpn.app - app.py:141 - interface transitioned: enter_search_query -> <PendingConfigurePredefinedServer search_query='Politechn'>
2021-05-09 10:58:57,469 - MainThread - INFO - eduvpn.app - app.py:130 - interface transitioning: <PendingConfigurePredefinedServer search_query='Politechn'> -> enter_search_query
2021-05-09 10:58:57,470 - MainThread - INFO - eduvpn.app - app.py:141 - interface transitioned: enter_search_query -> <PendingConfigurePredefinedServer search_query='Politechni'>
2021-05-09 10:58:57,721 - MainThread - INFO - eduvpn.app - app.py:130 - interface transitioning: <PendingConfigurePredefinedServer search_query='Politechni'> -> enter_search_query
2021-05-09 10:58:57,721 - MainThread - INFO - eduvpn.app - app.py:141 - interface transitioned: enter_search_query -> <PendingConfigurePredefinedServer search_query='Politechnika'>
2021-05-09 10:59:46,428 - MainThread - INFO - eduvpn.app - app.py:130 - interface transitioning: <PendingConfigurePredefinedServer search_query='Politechnika'> -> enter_search_query
2021-05-09 10:59:46,428 - MainThread - INFO - eduvpn.app - app.py:141 - interface transitioned: enter_search_query -> <PendingConfigurePredefinedServer search_query=''>
```

OS on which is installed eduVPN - **Zorin OS 15.3 (based on Ubuntu Bionic)**
**Connecting with WiFi
Tested on version 2.0.0-1**

### How to reproduce?
Run `eduvpn-cli` or `eduvpn-gui` with use of terminal.

**Comment by gijzelaerr** [comment]
looks like a bug in nacl, what version of that package comes with zorin?

**Comment by alvra** [comment]
Looks like issue #362, which is solved on master but the fix has not yet been released.
Maybe you can use an newer version of NaCl for now?

**Comment by arusf2011** [comment]
> looks like a bug in nacl, what version of that package comes with zorin?

It comes with ver `1.1.2-1build1`, so pretty old.
As far as I'm concerned Zorin didn't get update to latest LTS, for that reason I'm getting this error.
Anyway - decided to change distro. Thanks for help anyway.
