### ISSUE TITLE
My VPN stopped working - unable to use eduvpn to re-setup network manager

### ISSUE THREAD

**Issue by norrs** [eduvpn/python-eduvpn-client#380]
# Installation

How did you install the eduVPN client?

It was already installed, updated my Debian unstable (sid) apt index by `apt update` then `apt install --reinstall eduvpn-gui eduvpn-client` since it has stopped working.

# Version

What version of the client you are running? Try your package manager or otherwise `$ eduvpn-client -v`.

```
rockj@qhira:~$ eduvpn-cli -v
usage: eduvpn-cli [-h] {interactive,search,configure,refresh,list,activate,deactivate,status} ...
eduvpn-cli: error: unrecognized arguments: -v
rockj@qhira:~$ eduvpn-cli refresh
Traceback (most recent call last):
  File "/usr/bin/eduvpn-cli", line 11, in <module>
    load_entry_point('eduvpn-client==2.0.0', 'console_scripts', 'eduvpn-cli')()
  File "/usr/lib/python3/dist-packages/eduvpn/cli.py", line 139, in eduvpn
    parse_eduvpn(argv[1:])
  File "/usr/lib/python3/dist-packages/eduvpn/cli.py", line 105, in parse_eduvpn
    parsed.func(parsed)
  File "/usr/lib/python3/dist-packages/eduvpn/cli.py", line 26, in refresh
    actions.refresh()
  File "/usr/lib/python3/dist-packages/eduvpn/actions.py", line 23, in refresh
    uuid, auth_url, metadata = get_storage(check=True)
  File "/usr/lib/python3/dist-packages/eduvpn/storage.py", line 201, in get_storage
    raise Exception("no eduVPN uuid stored (yet)")
Exception: no eduVPN uuid stored (yet)
rockj@qhira:~$ eduvpn-cli interactive
INFO:eduvpn.remote:Requesting https://disco.eduvpn.org/v2/server_list.json
INFO:eduvpn.remote:Retrieving signature https://disco.eduvpn.org/v2/server_list.json.minisig
INFO:eduvpn.remote:verifying signature of https://disco.eduvpn.org/v2/server_list.json
ERROR:eduvpn.remote:Got exception  requesting https://disco.eduvpn.org/v2/server_list.json for server_list
Traceback (most recent call last):
  File "/usr/bin/eduvpn-cli", line 11, in <module>
    load_entry_point('eduvpn-client==2.0.0', 'console_scripts', 'eduvpn-cli')()
  File "/usr/lib/python3/dist-packages/eduvpn/cli.py", line 139, in eduvpn
    parse_eduvpn(argv[1:])
  File "/usr/lib/python3/dist-packages/eduvpn/cli.py", line 105, in parse_eduvpn
    parsed.func(parsed)
  File "/usr/lib/python3/dist-packages/eduvpn/cli.py", line 66, in interactive
    auth_url, display_name, support_contact, secure_internets = menu.interactive(args)
  File "/usr/lib/python3/dist-packages/eduvpn/menu.py", line 178, in interactive
    servers = list_servers(SERVER_URI)
  File "/usr/lib/python3/dist-packages/eduvpn/remote.py", line 74, in list_servers
    result = request(uri, verify=True)['server_list']
  File "/usr/lib/python3/dist-packages/eduvpn/remote.py", line 46, in request
    _ = validate(content=response.content, signature=signature)
  File "/usr/lib/python3/dist-packages/eduvpn/crypto.py", line 98, in validate
    raise BadSignatureError
nacl.exceptions.BadSignatureError
```

# OS/Distribution

What operating system/distribution and version you are running?

Debian unstable (sid) 

```
rockj@qhira:~$ dpkg -l | grep eduvpn
ii  eduvpn-client                                 2.0.0-1                         all          VPN client for educational networks
ii  eduvpn-client-data                            2.0.0-1                         all          VPN client for educational networks (data files)
ii  python3-eduvpn-client                         2.0.0-1                         all          eduVPN client (Python 3)
```
 

Is this related to https://github.com/eduvpn/python-eduvpn-client/issues/356 ?

**Comment by norrs** [comment]
Hm, looks my institution has another way of obtaining VPN credentials. From https://disco.eduvpn.org/v2/server_list.json I found `Unit` which again lists up https://unit.eduvpn.no/ . Here is an easy web application you can login to, and then you get easy access to download a openvpn profile which can easily be imported into network manager.

But I guess this bug above is still valid, but that was a workaround for me.

**Comment by gijzelaerr** [comment]
Did you also try the eduvpn GUI or only the CLI?

**Comment by efef** [comment]
@norrs We experienced a meta-data signing issue last Monday, that issue has been fixed. I expect this was related to your linux client signging error.  Can you please confirm this issue has 'gone' by now?

**Comment by gijzelaerr** [comment]
@efef i think we should improve that error message a bit with a description of what signature of what service is rejected and why.

**Comment by norrs** [comment]
When I started the eduvpn GUI client now, it was able to fetch the server list, and not failing on signature. I guess we can close this now.
