### ISSUE TITLE
Connexion still load details server

### ISSUE THREAD

**Issue by hedjour** [eduvpn/python-eduvpn-client#386]
# Installation

How did you install the eduVPN client?
 - By the debian/ubuntu repository

# Version

What version of the client you are running? Try your package manager or otherwise `$ eduvpn-client -v`.
```bash 
    eduvpn-gui -v
```
eduVPN Linux client version 0.0dev

# OS/Distribution

What operating system/distribution and version you are running?
Ubuntu 20.04.2 LTS

# Logs
Traceback (most recent call last):
```bash
2021-06-28 13:18:34,390 - load-server-info - DEBUG - requests_oauthlib.oauth2_session - oauth2_session.py:358 - Passing through key word arguments {'allow_redirects': True}.
2021-06-28 13:18:34,420 - load-server-info - DEBUG - urllib3.connectionpool - connectionpool.py:428 - https://XXXXXXXXXXX:443 "GET /vpn-user-portal/api.php/profile_list HTTP/1.1" 200 None
Exception in thread load-server-info:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/eduvpn/interface/event.py", line 101, in on_start_connection
    profiles = [Profile(**data) for data in remote.list_profiles(oauth_session, api_url)]
  File "/usr/lib/python3/dist-packages/eduvpn/interface/event.py", line 101, in <listcomp>
    profiles = [Profile(**data) for data in remote.list_profiles(oauth_session, api_url)]
TypeError: __init__() missing 1 required positional argument: 'default_gateway'
```
## Do you have a problem while adding a profile?

When I try to create a new profile the gui keep buffering on message : "The server details are being loaded"

**Comment by alvra** [comment]
Thanks for the bug report. I'm working on a fix that will be part of the next release.
Which server and profile were you connecting to when this happened?

**Comment by hedjour** [comment]
I try to connect on Poitiers University servers which is not listed in eduvpn software.

**Comment by hedjour** [comment]
Sorry but the bug still remain

**Comment by gijzelaerr** [comment]
What version did you try
