### ISSUE TITLE
probably bug in networkmanager or dbus package for fedora 26

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#42]
```
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/NetworkManager.py", line 77, in handle_signal
    receiver(sender, *(sargs + rargs), **rkwargs)
TypeError: can only concatenate list (not "tuple") to list
```

**Comment by gijzelaerr** [comment]
actually it also happens on ubuntu with a fresh install from pip using python3.

https://github.com/seveas/python-networkmanager/issues/41

**Comment by gijzelaerr** [comment]
maybe this can be solved by basing the package on the python2 version code.

**Comment by gijzelaerr** [comment]
nope, also happens with Python2.7.

**Comment by gijzelaerr** [comment]
fixed per https://github.com/eduvpn/python-eduvpn-client/commit/aaac20bdaa7ec3ee91e7599376047fb09f70748a
