### ISSUE TITLE
Can't start UI on Fedora 35

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#422]
```
parallels@fedora python-eduvpn-client]$ make eduvpn-gui 
./venv/bin/eduvpn-gui
Traceback (most recent call last):
  File "/home/parallels/python-eduvpn-client/eduvpn/ui/app.py", line 71, in do_startup
    self.app.initialize()
  File "/home/parallels/python-eduvpn-client/eduvpn/app.py", line 40, in initialize
    self.initialize_network()
  File "/home/parallels/python-eduvpn-client/eduvpn/app.py", line 63, in initialize_network
    self.session_transition('no_previous_session_found')
  File "/home/parallels/python-eduvpn-client/eduvpn/app.py", line 164, in session_transition
    self._base_transition(
  File "/home/parallels/python-eduvpn-client/eduvpn/app.py", line 137, in _base_transition
    state_machine.transition(
  File "/home/parallels/python-eduvpn-client/eduvpn/state_machine.py", line 174, in transition
    new_state = transition_func(*args, **kwargs)
  File "/home/parallels/python-eduvpn-client/eduvpn/session.py", line 84, in no_previous_session_found
    app.network_transition('no_previous_connection_found')
  File "/home/parallels/python-eduvpn-client/eduvpn/app.py", line 152, in network_transition
    self._base_transition(
  File "/home/parallels/python-eduvpn-client/eduvpn/app.py", line 137, in _base_transition
    state_machine.transition(
  File "/home/parallels/python-eduvpn-client/eduvpn/state_machine.py", line 176, in transition
    with self.trigger_callbacks(old_state, new_state):
  File "/usr/lib64/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/home/parallels/python-eduvpn-client/eduvpn/state_machine.py", line 188, in trigger_callbacks
    self._call_edge_callbacks(ENTER, old_state, new_state)
  File "/home/parallels/python-eduvpn-client/eduvpn/state_machine.py", line 262, in _call_edge_callbacks
    callback(old_state, new_state)
  File "/home/parallels/python-eduvpn-client/eduvpn/ui/app.py", line 171, in enter_NoActiveConnection
    if not self.window.is_visible():
AttributeError: 'NoneType' object has no attribute 'is_visible'
Traceback (most recent call last):
  File "/home/parallels/python-eduvpn-client/eduvpn/ui/app.py", line 81, in do_activate
    self.window = EduVpnGtkWindow(application=self)
  File "/home/parallels/python-eduvpn-client/eduvpn/ui/ui.py", line 153, in __init__
    self.app.connect_state_transition_callbacks(self, initialize=True)
  File "/home/parallels/python-eduvpn-client/eduvpn/app.py", line 125, in connect_state_transition_callbacks
    self.network_state_machine.trigger_initial_callbacks()
  File "/home/parallels/python-eduvpn-client/eduvpn/state_machine.py", line 192, in trigger_initial_callbacks
    with self.trigger_callbacks(self.initial_state, self.state):
  File "/usr/lib64/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/home/parallels/python-eduvpn-client/eduvpn/state_machine.py", line 188, in trigger_callbacks
    self._call_edge_callbacks(ENTER, old_state, new_state)
  File "/home/parallels/python-eduvpn-client/eduvpn/state_machine.py", line 262, in _call_edge_callbacks
    callback(old_state, new_state)
  File "/home/parallels/python-eduvpn-client/eduvpn/ui/app.py", line 171, in enter_NoActiveConnection
    if not self.window.is_visible():
AttributeError: 'NoneType' object has no attribute 'is_visible'
```

**Comment by martijnkruiten** [comment]
This worked for me when I had to install it on Fedora 35 a while back (I'm using the GUI daily):

```
sudo dnf groupinstall 'C Development Tools and Libraries'
sudo dnf install dbus-devel python-devel cairo-devel
python3 -m venv venv
venv/pip install "eduvpn-client[gui]"
```

I've just tested if it also works with `venv/pip install ".[gui]"` and with `make` and both of these work too on my system with latest version of the master branch.

**Comment by gijzelaerr** [comment]
i think we should then:
* add the missing deps to the `make dnf` target
* Improve the error message

**Comment by martijnkruiten** [comment]
On a clean installation I also had to do `sudo dnf install cairo-gobject-devel gobject-introspection-devel` and then I got the same error as you did. I don't know why it works on my installation.

**Comment by gijzelaerr** [comment]
strange, all the packages you list are installed by `make dnf` already as far as I can see. the `'C Development Tools and Libraries'` group install installs compiler tools, things we don't require I think.

**Comment by gijzelaerr** [comment]
This issue seems to be solved in #419

**Comment by gijzelaerr** [comment]
Nope, i just made an RPM from the `updates` branch and this gives again the same problem once started, so it seems unrelated to #419.

**Comment by martijnkruiten** [comment]
> strange, all the packages you list are installed by `make dnf` already as far as I can see. the `'C Development Tools and Libraries'` group install installs compiler tools, things we don't require I think.

Yes, I didn't use `make dnf` at first, because I only learned about that option later, so I didn't mean to imply that those packages were missing from the makefile. I still use the GUI that I built previously on Fedora 35 every day without issues, but on a clean installation of Fedora 35 I get the same error as you.

**Comment by gijzelaerr** [comment]
> Nope, i just made an RPM from the `updates` branch and this gives again the same problem once started, so it seems unrelated to #419.

before we close this issue I want to make sure this doesn't happen when building an RPM.

**Comment by gijzelaerr** [comment]
this seems to be resolved.
