### ISSUE TITLE
Loading UI files broken

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#423]
When the failing test in #421 is disabled we can build a package, but the codes look for the UI files in the wrong location somehow:
```
[parallels@fedora noarch]$ /usr/bin/eduvpn-gui 
Traceback (most recent call last):
  File "/usr/bin/eduvpn-gui", line 33, in <module>
    sys.exit(load_entry_point('eduvpn-client==2.1.0', 'gui_scripts', 'eduvpn-gui')())
  File "/usr/bin/eduvpn-gui", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/eduvpn/ui/__main__.py", line 10, in <module>
    from ..ui.app import EduVpnGtkApplication
  File "/usr/lib/python3.10/site-packages/eduvpn/ui/app.py", line 16, in <module>
    from .ui import EduVpnGtkWindow
  File "/usr/lib/python3.10/site-packages/eduvpn/ui/ui.py", line 71, in <module>
    class EduVpnGtkWindow(Gtk.ApplicationWindow):
  File "/usr/lib64/python3.10/site-packages/gi/_gtktemplate.py", line 300, in __call__
    bytes_ = GLib.Bytes.new(file_.load_contents()[1])
gi.repository.GLib.Error: g-io-error-quark: Error opening file /home/parallels/rpmbuild/RPMS/noarch/share/eduvpn/builder/mainwindow.ui: No such file or directory (1)
```

**Comment by gijzelaerr** [comment]
If I cd to `/usr` it works. The paths are loaded from a relative path without any attempt to discover the right location:

https://github.com/eduvpn/python-eduvpn-client/blame/master/eduvpn/ui/ui.py#L70

**Comment by gijzelaerr** [comment]
This is still broken for the RPM build:
```
[parallels@fedora ~]$ eduvpn-gui 
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/eduvpn/ui/app.py", line 80, in do_activate
    self.window = EduVpnGtkWindow(application=self)
  File "/usr/lib/python3.10/site-packages/eduvpn/ui/ui.py", line 138, in __init__
    os.chdir('share/eduvpn/builder')
FileNotFoundError: [Errno 2] No such file or directory: 'share/eduvpn/builder'
```

while the UI files are located here:
```
[parallels@fedora ~]$ ls -al /usr/share/eduvpn/builder/mainwindow.ui
-rw-r--r--. 1 root root 47716 Dec  2 08:44 /usr/share/eduvpn/builder/mainwindow.ui
```

**Comment by gijzelaerr** [comment]
The app should never call `os.chdir()`, this should definitely be removed.

**Comment by alvra** [comment]
Does the change in #429 resolve this issue?

**Comment by gijzelaerr** [comment]
I think the problem is the Gtk.Template decorator, somehow this resolved files differently from the old manual gbuilder UI file loading we used before.

**Comment by gijzelaerr** [comment]
The long-term solution would be to start using `GResources` to manage things like image assets, but that is out of scope for this release. The other solution would be to switch back to the old way of loading UI files, but that requires refactoring. Doing a `chdir` is a hack in my opinion, but it does solve the problem for now. 

made a new issue for this https://github.com/eduvpn/python-eduvpn-client/issues/433
