### ISSUE TITLE
Time data format error on Ubuntu 18.04

### ISSUE THREAD

**Issue by jwijenbergh** [eduvpn/python-eduvpn-client#462]
Time data format error when restarting the application, see the log

# Installation

How did you install the eduVPN client?

Git
# Version

What version of the client you are running? Try your package manager or otherwise `$ eduvpn-client -v`.

master
# OS/Distribution

What operating system/distribution and version you are running?

Ubuntu 18.04
# Logs

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/eduvpn_client-2.2.1-py3.6.egg/eduvpn/ui/app.py", line 83, in do_activate
    self.app.initialize()
  File "/usr/local/lib/python3.6/dist-packages/eduvpn_client-2.2.1-py3.6.egg/eduvpn/app.py", line 39, in initialize
    self.initialize_network()
  File "/usr/local/lib/python3.6/dist-packages/eduvpn_client-2.2.1-py3.6.egg/eduvpn/app.py", line 59, in initialize_network
    validity = storage.get_current_validity(server.oauth_login_url)
  File "/usr/local/lib/python3.6/dist-packages/eduvpn_client-2.2.1-py3.6.egg/eduvpn/storage.py", line 145, in get_current_validity
    metadata = get_current_metadata(auth_url)
  File "/usr/local/lib/python3.6/dist-packages/eduvpn_client-2.2.1-py3.6.egg/eduvpn/storage.py", line 123, in get_current_metadata
    created = deserialize_datetime(created)
  File "/usr/local/lib/python3.6/dist-packages/eduvpn_client-2.2.1-py3.6.egg/eduvpn/storage.py", line 105, in deserialize_datetime
    dt = datetime.strptime(value, format)
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2022-02-22T13:35:18+00:00' does not match format '%Y-%m-%dT%H:%M:%S%z'
```

**Comment by alvra** [comment]
Good find!
