### ISSUE TITLE
Deactivation in GUI leads to error on console

### ISSUE THREAD

**Issue by paulmelis** [eduvpn/python-eduvpn-client#469]
Split off from #467.

# Installation

From this repo, per readme instructions

# Version

45c58ec0108bd2dfc11d082fce38c2239a1c220e

# OS/Distribution

Arch Linux

# Logs

```
(venv) melis@juggle 11:18:~/c/python-eduvpn-client$ eduvpn-gui 
2022-03-22 11:18:41,211 - MainThread - INFO - eduvpn.ui.ui - ui.py:580 - selection empty
2022-03-22 11:18:41,211 - MainThread - INFO - eduvpn.ui.ui - ui.py:580 - selection empty
2022-03-22 11:18:41,212 - MainThread - INFO - eduvpn.ui.ui - ui.py:580 - selection empty
2022-03-22 11:18:41,226 - init-server-db - INFO - eduvpn.remote - remote.py:23 - Requesting https://disco.eduvpn.org/v2/server_list.json
2022-03-22 11:18:41,368 - init-server-db - INFO - eduvpn.remote - remote.py:37 - Retrieving signature https://disco.eduvpn.org/v2/server_list.json.minisig
2022-03-22 11:18:41,479 - init-server-db - INFO - eduvpn.remote - remote.py:44 - verifying signature of https://disco.eduvpn.org/v2/server_list.json
2022-03-22 11:18:41,480 - init-server-db - INFO - eduvpn.remote - remote.py:23 - Requesting https://disco.eduvpn.org/v2/organization_list.json
2022-03-22 11:18:41,659 - init-server-db - INFO - eduvpn.remote - remote.py:37 - Retrieving signature https://disco.eduvpn.org/v2/organization_list.json.minisig
2022-03-22 11:18:41,777 - init-server-db - INFO - eduvpn.remote - remote.py:44 - verifying signature of https://disco.eduvpn.org/v2/organization_list.json
2022-03-22 11:18:42,845 - MainThread - INFO - eduvpn.ui.ui - ui.py:580 - selection empty
2022-03-22 11:18:42,845 - MainThread - INFO - eduvpn.ui.ui - ui.py:580 - selection empty
2022-03-22 11:18:42,846 - oauth-refresh - INFO - eduvpn.remote - remote.py:23 - Requesting https://surf.eduvpn.nl/.well-known/vpn-user-portal
2022-03-22 11:18:43,002 - load-server-info - INFO - eduvpn.remote - remote.py:23 - Requesting https://surf.eduvpn.nl/.well-known/vpn-user-portal
2022-03-22 11:18:43,129 - configure-connection - INFO - eduvpn.remote - remote.py:23 - Requesting https://surf.eduvpn.nl/.well-known/vpn-user-portal
2022-03-22 11:18:43,362 - MainThread - INFO - eduvpn.nm - nm.py:265 - writing ovpn configuration to Network Manager
2022-03-22 11:18:43,362 - MainThread - INFO - eduvpn.nm - nm.py:188 - Writing configuration to /tmp/tmpbfeg_wqz/eduVPN.ovpn
2022-03-22 11:18:43,558 - MainThread - INFO - eduvpn.nm - nm.py:221 - Updating existing connection with new configuration
2022-03-22 11:18:43,580 - MainThread - INFO - eduvpn.interface.event - event.py:187 - Finished saving network manager config: <Gio.Task object at 0x7fcbe37ad300 (GTask at 0x55cd21e02100)>
2022-03-22 11:18:43,583 - MainThread - INFO - eduvpn.nm - nm.py:354 - setting default gateway: False
2022-03-22 11:18:43,601 - MainThread - INFO - eduvpn.nm - nm.py:286 - activate_connection uuid: c13b19c5-3dbf-485b-b353-8a9be1d55caa connection: <NM.RemoteConnection object at 0x7fcbe37ac740 (NMRemoteConnection at 0x55cd21d011f0)>
2022-03-22 11:18:43,675 - MainThread - INFO - eduvpn.nm - nm.py:301 - activate_connection_async result: <NM.VpnConnection object at 0x7fcbe045fa40 (NMVpnConnection at 0x55cd21f81370)>

<deactivate in GUI with the 0/1 switch>

2022-03-22 11:18:53,305 - stop-connection - INFO - eduvpn.remote - remote.py:23 - Requesting https://surf.eduvpn.nl/.well-known/vpn-user-portal
Traceback (most recent call last):
  File "/home/melis/c/python-eduvpn-client/eduvpn/ui/ui.py", line 616, in on_switch_connection_state
    self.app.interface_transition('deactivate_connection')
  File "/home/melis/c/python-eduvpn-client/eduvpn/app.py", line 172, in interface_transition
    self._base_transition(
  File "/home/melis/c/python-eduvpn-client/eduvpn/app.py", line 133, in _base_transition
    state_machine.transition(
  File "/home/melis/c/python-eduvpn-client/eduvpn/state_machine.py", line 174, in transition
    new_state = transition_func(*args, **kwargs)
  File "/home/melis/c/python-eduvpn-client/eduvpn/interface/state.py", line 364, in deactivate_connection
    app.network_transition('disconnect')
  File "/home/melis/c/python-eduvpn-client/eduvpn/app.py", line 148, in network_transition
    self._base_transition(
  File "/home/melis/c/python-eduvpn-client/eduvpn/app.py", line 133, in _base_transition
    state_machine.transition(
  File "/home/melis/c/python-eduvpn-client/eduvpn/state_machine.py", line 176, in transition
    with self.trigger_callbacks(old_state, new_state):
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/home/melis/c/python-eduvpn-client/eduvpn/state_machine.py", line 188, in trigger_callbacks
    self._call_edge_callbacks(ENTER, old_state, new_state)
  File "/home/melis/c/python-eduvpn-client/eduvpn/state_machine.py", line 262, in _call_edge_callbacks
    callback(old_state, new_state)
  File "/home/melis/c/python-eduvpn-client/eduvpn/ui/app.py", line 153, in enter_DisconnectedState
    self.connection_notification.hide()
  File "/home/melis/c/python-eduvpn-client/eduvpn/notify.py", line 32, in hide
    self.notification.close()  # type: ignore
gi.repository.GLib.GError: notification-daemon-error-quark: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._notification_2ddaemon_2derror_2dquark.Code100: 0 is not a valid notification ID (100)
```

I see no messages in the journalctl output when I run the deactivate command, seems to get stuck before doing anything.

What extra information would you need on my setup?

**Comment by paulmelis** [comment]
For starters, this is with NetworkManager 1.36.2-1, openvpn 2.5.5-1, networkmanager-openvpn 1.8.18-1

**Comment by gijzelaerr** [comment]
@paulmelis is this still an issue for you with the latest pre-release version in the master branch?

**Comment by paulmelis** [comment]
Nope, seems to be gone with the git head I just tried
