### ISSUE TITLE
Exception while connecting (AttributeError: 'str' object has no attribute 'write')

### ISSUE THREAD

**Issue by paulmelis** [eduvpn/python-eduvpn-client#470]
# Installation

From this repo with git clone, virtualenv, as per readme

# Version

45c58ec0108bd2dfc11d082fce38c2239a1c220e

# OS/Distribution

Arch Linux

# Logs

## Do you have a problem during connecting?

The exception below happens after allowing the connection in the browser.

```
(venv) melis@juggle 15:29:~/c/python-eduvpn-client$ eduvpn-cli activate
WARNING:/home/melis/c/python-eduvpn-client/eduvpn/actions.py:token invalid: (invalid_grant) "refresh_token" is no longer authorized
INFO:eduvpn.oauth2.http:listening for a request at 127.0.0.1:33157...
INFO:eduvpn.oauth2.http:received a request /callback?code=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsImtpZCI6IjRhNERITlZaM3ZjTHYyb3hlREJBNFVOaUlsNUJEUkhnbExUUlpvcFREVnMifQ.eyJ2Ijo1LCJ0eXBlIjoiYXV0aG9yaXphdGlvbl9jb2RlIiwiYXV0aF9rZXkiOiI2OTcwYTcxYjAwY2M3YjJhYzY4Yjk5OTk2Yzk3Yzg0OCIsInVzZXJfaWQiOiJodHRwczpcL1wvZW5naW5lLnN1cmZjb25leHQubmxcL2F1dGhlbnRpY2F0aW9uXC9pZHBcL21ldGFkYXRhIWh0dHBzOlwvXC9zdXJmLmVkdXZwbi5ubFwvc2FtbCExNmMyMTZjYzgzMWM4YTI2OTM0ZThlNWVmMTE4ZDIyOWI2NTI3NTk1IiwiY2xpZW50X2lkIjoib3JnLmVkdXZwbi5hcHAubGludXgiLCJzY29wZSI6ImNvbmZpZyIsInJlZGlyZWN0X3VyaSI6Imh0dHA6XC9cLzEyNy4wLjAuMTozMzE1N1wvY2FsbGJhY2siLCJjb2RlX2NoYWxsZW5nZSI6ImJTYm5LNld3NDlsSHBwOTl4cVhTY3lpNTYzbnNBMmxtRURCS1l1dlR4ejQiLCJleHBpcmVzX2F0IjoiMjAyMi0wMy0yOVQxMzozNToxNSswMDowMCJ9.NMip_Bkmo2X1pfNkUihDTtRzRIzibErCl9owqoiz8BIstGvRVhpV3dz7QUPAZX73_FQul8xcNd4CQ-3ix4uNCg&state=9xJmslC8Kv2rrNkKL757gipMqTaPSR
127.0.0.1 - - [29/Mar/2022 15:30:15] "GET /callback?code=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsImtpZCI6IjRhNERITlZaM3ZjTHYyb3hlREJBNFVOaUlsNUJEUkhnbExUUlpvcFREVnMifQ.eyJ2Ijo1LCJ0eXBlIjoiYXV0aG9yaXphdGlvbl9jb2RlIiwiYXV0aF9rZXkiOiI2OTcwYTcxYjAwY2M3YjJhYzY4Yjk5OTk2Yzk3Yzg0OCIsInVzZXJfaWQiOiJodHRwczpcL1wvZW5naW5lLnN1cmZjb25leHQubmxcL2F1dGhlbnRpY2F0aW9uXC9pZHBcL21ldGFkYXRhIWh0dHBzOlwvXC9zdXJmLmVkdXZwbi5ubFwvc2FtbCExNmMyMTZjYzgzMWM4YTI2OTM0ZThlNWVmMTE4ZDIyOWI2NTI3NTk1IiwiY2xpZW50X2lkIjoib3JnLmVkdXZwbi5hcHAubGludXgiLCJzY29wZSI6ImNvbmZpZyIsInJlZGlyZWN0X3VyaSI6Imh0dHA6XC9cLzEyNy4wLjAuMTozMzE1N1wvY2FsbGJhY2siLCJjb2RlX2NoYWxsZW5nZSI6ImJTYm5LNld3NDlsSHBwOTl4cVhTY3lpNTYzbnNBMmxtRURCS1l1dlR4ejQiLCJleHBpcmVzX2F0IjoiMjAyMi0wMy0yOVQxMzozNToxNSswMDowMCJ9.NMip_Bkmo2X1pfNkUihDTtRzRIzibErCl9owqoiz8BIstGvRVhpV3dz7QUPAZX73_FQul8xcNd4CQ-3ix4uNCg&state=9xJmslC8Kv2rrNkKL757gipMqTaPSR HTTP/1.1" 200 -
INFO:eduvpn.remote:Requesting https://surf.eduvpn.nl/.well-known/vpn-user-portal
INFO:eduvpn.nm:calling action with CLI mainloop
INFO:eduvpn.nm:writing configuration to Network Manager
INFO:eduvpn.storage:Writing configuration to /tmp/tmpzu9pgbi0/eduVPN.ovpn
Traceback (most recent call last):
  File "/home/melis/c/python-eduvpn-client/venv/bin/eduvpn-cli", line 33, in <module>
    sys.exit(load_entry_point('eduvpn-client==2.2.1', 'console_scripts', 'eduvpn-cli')())
  File "/home/melis/c/python-eduvpn-client/eduvpn/cli.py", line 139, in eduvpn
    parse_eduvpn(argv[1:])
  File "/home/melis/c/python-eduvpn-client/eduvpn/cli.py", line 105, in parse_eduvpn
    parsed.func(parsed)
  File "/home/melis/c/python-eduvpn-client/eduvpn/cli.py", line 30, in activate
    actions.activate()
  File "/home/melis/c/python-eduvpn-client/eduvpn/actions.py", line 129, in activate
    refresh()
  File "/home/melis/c/python-eduvpn-client/eduvpn/actions.py", line 45, in refresh
    save_connection_with_mainloop(config, key, cert)
  File "/home/melis/c/python-eduvpn-client/eduvpn/nm.py", line 430, in save_connection_with_mainloop
    action_with_mainloop(
  File "/home/melis/c/python-eduvpn-client/eduvpn/nm.py", line 425, in action_with_mainloop
    action(callback=quit_loop)
  File "/home/melis/c/python-eduvpn-client/eduvpn/nm.py", line 431, in <lambda>
    action=lambda callback: save_connection_with_config(get_client(), config, private_key, certificate, callback))
  File "/home/melis/c/python-eduvpn-client/eduvpn/nm.py", line 260, in save_connection_with_config
    return save_connection(client, ovpn, private_key, certificate, callback)
  File "/home/melis/c/python-eduvpn-client/eduvpn/nm.py", line 246, in save_connection
    new_con = import_ovpn_and_certificate(ovpn, private_key, certificate)
  File "/home/melis/c/python-eduvpn-client/eduvpn/nm.py", line 176, in import_ovpn_and_certificate
    write_ovpn(ovpn, private_key, certificate, target)
  File "/home/melis/c/python-eduvpn-client/eduvpn/storage.py", line 256, in write_ovpn
    ovpn.write(f)
  File "/home/melis/c/python-eduvpn-client/eduvpn/ovpn.py", line 95, in write
    item.write(file)
AttributeError: 'str' object has no attribute 'write'
```

**Comment by dahooz** [comment]
I also ran into this issue while generating a profile for the NetworkManager with `eduvpn-cli configure`.

I fixed it by reversing the variable usage in `Ovpn.write()`. For my use-case the tool works as intended when using my patch.

**Comment by paulmelis** [comment]
Ouch, nasty typo, thanks for the patch

**Comment by paulmelis** [comment]
Indeed, the patch makes activation work for me again

**Comment by gijzelaerr** [comment]
thanks @dahooz! unfortunately the test suite fails

**Comment by dahooz** [comment]
> thanks @dahooz! unfortunately the test suite fails

I've updated the pull request based on the comments by @alvra and @jwijenbergh . Now the test suite does not run at all. I assume that you reconfigured it because it requires some permissions I do not have.
