### ISSUE TITLE
connection_info_stats is None

### ISSUE THREAD

**Issue by alvra** [eduvpn/python-eduvpn-client#471]
I'm seeing exception tracebacks in the logs when connecting/disconnecting from a server with the connection stats tab opened.

Running the current last commit in the `wireguard` branch (7a851693d4c18ef7c0b3339dca4b8cf5f3927758) on Ubuntu 20.

```
Exception in thread run-periodically:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/shared-eduvpn/source/eduvpn/utils.py", line 112, in run_periodic_thread
    elif func() is False:
  File "/home/user/shared-eduvpn/source/eduvpn/ui/ui.py", line 634, in update_connection_info_callback
    assert self.connection_info_stats
AssertionError
```

```
Exception in thread run-periodically:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread run-periodically:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/shared-eduvpn/source/eduvpn/utils.py", line 112, in run_periodic_thread
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/shared-eduvpn/source/eduvpn/utils.py", line 112, in run_periodic_thread
    elif func() is False:
  File "/home/user/shared-eduvpn/source/eduvpn/ui/ui.py", line 637, in update_connection_info_callback
    elif func() is False:
  File "/home/user/shared-eduvpn/source/eduvpn/ui/ui.py", line 637, in update_connection_info_callback
    ipv4 = self.connection_info_stats.ipv4
AttributeError: 'NoneType' object has no attribute 'ipv4'
    ipv4 = self.connection_info_stats.ipv4
AttributeError: 'NoneType' object has no attribute 'ipv4'
```
Seems like the thread is running twice in the latter case.

**Comment by alvra** [comment]
I've added a commit to the WireGuard PR #466  (213881a5df4badc35e7afe21babf034b5995d38e) that seems to resolve this issue.

**Comment by alvra** [comment]
Unfortunately, the issue is not resolved yet. Clicking the back button while connected with the stats open, gives the same AssertionError.

```
2022-04-04 18:35:11,964 - MainThread - DEBUG - eduvpn.app - app.py:141 - network transitioned: set_connecting -> <ConnectingState>
2022-04-04 18:35:12,967 - MainThread - DEBUG - eduvpn.app - app.py:130 - network transitioning: <ConnectingState> -> set_connecting
2022-04-04 18:35:12,967 - MainThread - DEBUG - eduvpn.app - app.py:141 - network transitioned: set_connecting -> <ConnectingState>
2022-04-04 18:35:13,062 - MainThread - DEBUG - eduvpn.app - app.py:130 - network transitioning: <ConnectingState> -> set_connected
2022-04-04 18:35:13,228 - MainThread - DEBUG - eduvpn.app - app.py:141 - network transitioned: set_connected -> <ConnectedState>
2022-04-04 18:35:13,230 - MainThread - DEBUG - eduvpn.app - app.py:130 - network transitioning: <ConnectedState> -> set_connected
2022-04-04 18:35:13,236 - MainThread - DEBUG - eduvpn.app - app.py:141 - network transitioned: set_connected -> <ConnectedState>
2022-04-04 18:35:13,237 - MainThread - DEBUG - eduvpn.app - app.py:130 - network transitioning: <ConnectedState> -> set_connecting
2022-04-04 18:35:13,405 - MainThread - DEBUG - eduvpn.app - app.py:141 - network transitioned: set_connecting -> <ConnectingState>
2022-04-04 18:35:13,412 - MainThread - DEBUG - eduvpn.app - app.py:130 - network transitioning: <ConnectingState> -> set_connected
2022-04-04 18:35:13,464 - MainThread - DEBUG - eduvpn.app - app.py:141 - network transitioned: set_connected -> <ConnectedState>
2022-04-04 18:35:16,743 - MainThread - DEBUG - eduvpn.ui.ui - ui.py:560 - clicked on go back
2022-04-04 18:35:16,745 - MainThread - DEBUG - eduvpn.app - app.py:130 - interface transitioning: <ConnectionStatus> -> go_back
2022-04-04 18:35:16,752 - MainThread - DEBUG - eduvpn.app - app.py:141 - interface transitioned: go_back -> <MainState servers=[...]>
Exception in thread run-periodically:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/shared-eduvpn/source_wireguard2/eduvpn/utils.py", line 112, in run_periodic_thread
    elif func() is False:
  File "/home/user/shared-eduvpn/source_wireguard2/eduvpn/ui/ui.py", line 634, in update_connection_info_callback
    assert self.connection_info_stats
AssertionError
```
