### ISSUE TITLE
Installation succeeds but running the tool fails on Linux Mint 20.x

### ISSUE THREAD

**Issue by FLomb** [eduvpn/python-eduvpn-client#538]
# Installation

I've tried several installation modes: 

- The one suggested for Linux Mint 20.1
- Via pip, stable version
- Via pip, bleeding-edge version

All installed successfully, but failed running.

# Version

The latest version, 4.4.1

# OS/Distribution

Linux Mint 20.3 (but the same problem also arose with Mint 20.1)

# Logs

## Do you have a problem while adding before connecting?

```
A fatal error occurred
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/eduvpn_common/loader.py", line 48, in load_lib
    lib = cdll.LoadLibrary(libfile)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /lib/libeduvpn_common-1.1.0.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fl/.local/lib/python3.8/site-packages/eduvpn/ui/__main__.py", line 29, in main_loop
    _common = common.EduVPN(*variant_settings, language=country())
  File "/usr/lib/python3/dist-packages/eduvpn_common/main.py", line 54, in __init__
    self.lib = load_lib()
  File "/usr/lib/python3/dist-packages/eduvpn_common/loader.py", line 51, in load_lib
    lib = cdll.LoadLibrary(str(pathlib.Path(__file__).parent / "lib" / libfile))
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/python3/dist-packages/eduvpn_common/lib/libeduvpn_common-1.1.0.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
```

**Comment by jwijenbergh** [comment]
> The one suggested for Linux Mint 20.1
The docs only mention Linux mint 21.x, not 20.x.

Let me install a linux mint 20.x VM

**Comment by FLomb** [comment]
> > The one suggested for Linux Mint 20.1
> 
> The docs only mention Linux mint 21.x, not 20.x.
> 
> Let me install a linux mint 20.x VM

Yes, sorry, I meant I tried the docs for mint 21.x.


> The pip client works on a fresh VM for me (linux mint 20.3), did you fully uninstall the other client when trying the pip version? Are you launching the pip version from ~/.local/bin/eduvpn-gui?

Yes, I uninstalled the other client. First, I did so following your suggestions for Ubuntu if upgrading from 3.x to 4.x, which suggested removing various items before installing a new version. Then, each time before trying a new installation with a different method, I made sure to either do `pip uninstall eduvpn-client` (for installations via pip) or to remove it from my Linux packages (for installation methods via Linux). 

Since I need this quite urgently, I even tried going back to an older version. However, what was working for me was version 3.1.1, which does not seem to be allowed during the installation despite existing as a tag in this repo. The closest allowed is 3.1.0, which successfully installs and successfully runs. Nonetheless, it seems to be 'ineffective': despite being connected through my institution, I fail to access the services I was accessing before.

**Comment by jwijenbergh** [comment]
> Yes, sorry, I meant I tried the docs for mint 21.x.

Ah yes mint 21.x is based on ubuntu 22.04 and mint 20.x is based on ubuntu 20.04 so this won't work unfortunately.

Could you try to remove: `/usr/lib/python3/dist-packages/eduvpn_common/lib/libeduvpn_common-1.1.0.so` and reinstall the pip version? If this fails please give me the stacktrace. It should loud the .so file from the following location:

`~/.local/lib/python3.8/site-packages/eduvpn_common/lib/libeduvpn_common-1.1.0.so`

It seems that in your case the old client (from apt) was not properly cleaned up.

> Since I need this quite urgently, I even tried going back to an older version. However, what was working for me was version 3.1.1, which does not seem to be allowed during the installation despite existing as a tag in this repo. The closest allowed is 3.1.0, which successfully installs and successfully runs. Nonetheless, it seems to be 'ineffective': despite being connected through my institution, I fail to access the services I was accessing before.

I have spent significant effort on the newer clients so I would recommend that you still try to get them to work. The reason we don't have official packages for these older distros is that we intent to support the latest 2 ubuntu LTS (so max linux mint 21) and provide support for the rest via pip.

As a last resort you can try to follow the debian bullseye instructions which is what linux mint 20 (and in turn ubuntu 20) is based on.

**Comment by FLomb** [comment]
Hi,

I've tried removing the files you suggested. The first was not there (as expected, since launching the software crashed due to not finding that file); the second was there and was removed. Then I installed via pip, and ended up with the same error as before.

Hence, I tried cleaning it all up again and installing it based on Debian 11's instructions, as you suggested. Same outcome.

How can I provide you with the stacktrace?

**Comment by FLomb** [comment]
Then I believe it's still the same: 
```
A fatal error occurred
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/eduvpn_common/loader.py", line 48, in load_lib
    lib = cdll.LoadLibrary(libfile)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libeduvpn_common-1.1.0.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fl/.local/lib/python3.8/site-packages/eduvpn/ui/__main__.py", line 29, in main_loop
    _common = common.EduVPN(*variant_settings, language=country())
  File "/usr/lib/python3/dist-packages/eduvpn_common/main.py", line 54, in __init__
    self.lib = load_lib()
  File "/usr/lib/python3/dist-packages/eduvpn_common/loader.py", line 51, in load_lib
    lib = cdll.LoadLibrary(str(pathlib.Path(__file__).parent / "lib" / libfile))
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/python3/dist-packages/eduvpn_common/lib/libeduvpn_common-1.1.0.so: cannot open shared object file: No such file or directory
```

**Comment by jwijenbergh** [comment]
This is a different error message. Now it cannot find the eduvpn_common file. Please give me the output of 

```bash
sudo find / -iname "*eduvpn_common-1.1.0.so" 2>/dev/null
```

**Comment by FLomb** [comment]
The above command produces no output

**Comment by jwijenbergh** [comment]
I don't understand, when you install through pip or the debian apt install instructions there should be a file with that name so I don't know what's going on. I would suggest to try on a clean machine because I cannot reproduce it on linux mint 20.x. See the screenshot 
![image](https://github.com/eduvpn/python-eduvpn-client/assets/46386452/cf7b5978-4ee8-43ac-b177-cd0221fe4baf)

**Comment by FLomb** [comment]
Hi,

The command above did not work. It says that installing libeduvpn-common is not possible:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Reinstallation of libeduvpn-common is not possible, it cannot be downloaded.
The following packages were automatically installed and are no longer required:
  linux-headers-5.4.0-139 linux-headers-5.4.0-139-generic
  linux-image-5.4.0-139-generic linux-modules-5.4.0-139-generic
  linux-modules-extra-5.4.0-139-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.
```

The output for the command you requested is the following: `deb [arch=amd64 signed-by=/usr/share/keyrings/eduvpn-v4.gpg] https://app.eduvpn.org/linux/v4/deb/ bullseye main`

The `/etc/apt/sources.list.d/` contains an `eduvpn-v4.list` file. The `/etc/apt/sources.list` is essentially empty except for some comments

**Comment by jwijenbergh** [comment]
Please give me the output of ```sudo apt update```

**Comment by FLomb** [comment]
There are some error messages there, but they are related to other, unrelated software, as far as I can see:

```
Hit:1 http://ppa.launchpad.net/peek-developers/stable/ubuntu focal InRelease
Hit:2 http://packages.microsoft.com/repos/code stable InRelease
Hit:3 http://archive.canonical.com/ubuntu focal InRelease                      
Hit:5 https://app.eduvpn.org/linux/v4/deb bullseye InRelease                   
Hit:6 https://repo.skype.com/deb stable InRelease                              
Get:7 https://packages.microsoft.com/repos/ms-teams stable InRelease [5931 B]  
Get:8 https://deb.opera.com/opera-stable stable InRelease [2590 B]             
Hit:9 http://archive.ubuntu.com/ubuntu focal InRelease                         
Hit:10 https://download.owncloud.com/desktop/ownCloud/stable/2.7.6.3261/linux/Ubuntu_20.04  InRelease
Hit:11 http://security.ubuntu.com/ubuntu focal-security InRelease              
Ign:12 http://packages.linuxmint.com una InRelease                             
Hit:13 http://archive.ubuntu.com/ubuntu focal-updates InRelease                
Get:14 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]     
Hit:15 http://packages.linuxmint.com una Release                               
Get:4 https://download.owncloud.org/download/repositories/production/Ubuntu_20.04  InRelease
Err:4 https://download.owncloud.org/download/repositories/production/Ubuntu_20.04  InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Err:8 https://deb.opera.com/opera-stable stable InRelease                      
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 24A1004B1F11DCC9
Err:10 https://download.owncloud.com/desktop/ownCloud/stable/2.7.6.3261/linux/Ubuntu_20.04  InRelease
  The following signatures were invalid: EXPKEYSIG 0700205DFD41A71A devel OBS Project <devel@s2.owncloud.com>
Hit:17 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease 
Reading package lists... Done
E: Failed to fetch http://download.owncloud.org/download/repositories/production/Ubuntu_20.04/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'http://download.owncloud.org/download/repositories/production/Ubuntu_20.04  InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://deb.opera.com/opera-stable stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 24A1004B1F11DCC9
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://download.owncloud.com/desktop/ownCloud/stable/2.7.6.3261/linux/Ubuntu_20.04  InRelease: The following signatures were invalid: EXPKEYSIG 0700205DFD41A71A devel OBS Project <devel@s2.owncloud.com>

```

**Comment by jwijenbergh** [comment]
I would fix your apt update errors first before continuing. You have multiple repositories that are failing to update. Is there any way you can test a fresh VM/install?

**Comment by jwijenbergh** [comment]
I have added support for linux mint 20.x https://python-eduvpn-client.readthedocs.io/en/latest/installation.html#linux-mint-20-x
