### ISSUE TITLE
RPM doesn't build for CentOS

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#55]
```
Mock Version: 1.4.4
ENTER ['do'](['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/eduvpn-client.spec'], chrootPath='/var/lib/mock/603070-epel-7-x86_64/root'env={'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'en_US.UTF-8'}shell=Falselogger=<mockbuild.trace_decorator.getLog object at 0x7efde1090208>timeout=0uid=1001gid=135user='mockbuild'nspawn_args=['--private-network']printOutput=True)
Executing command: ['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/eduvpn-client.spec'] with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'en_US.UTF-8'} and shell False
error: line 37: Unknown tag: %python_provide: ERROR: python3-eduvpn-client not recognized.
Building target platforms: x86_64
Building for target x86_64
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/util.py", line 590, in do
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed: 
 # bash --login -c /usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/eduvpn-client.spec
```

**Comment by gijzelaerr** [comment]
Ok there are various issues.

1. Some macros are not understood, which is an easy fix
2. CentOS 7 doesn't include python3, we could do without
3. Centos 7 doesn't contain `python2-pydbus` and `python2-pynacl`, which is much harder to solve.

So leaving this issue open for now.

**Comment by gijzelaerr** [comment]
actually it almost works for python2, only python-pynacl is missing

https://github.com/eduvpn/python-eduvpn-client/blob/master/rpm/centos7.spec

**Comment by gijzelaerr** [comment]
we can make an RPM for python-pynacl quite easily:

https://github.com/gijzelaerr/python-pynacl/blob/centos7/python-pynacl.spec

**Comment by gijzelaerr** [comment]
This used to be an issue also: https://github.com/eduvpn/python-eduvpn-client/issues/138

but for now we have disabled `connect-timeout` in the configuration. https://github.com/eduvpn/python-eduvpn-client/issues/139

This makes it easier to support centos now.

**Comment by gijzelaerr** [comment]
this is working now.
```
$ sudo yum install  yum-plugin-copr
$ sudo yum copr enable gijzelaerr/eduvpn-client
$ sudo yum install eduvpn-client
```
