### ISSUE TITLE
Pip installation fails (Pipx works)

### ISSUE THREAD

**Issue by HannoSpreeuw** [eduvpn/python-eduvpn-client#557]
# Installation

yay -S python-eduvpn-client

# Version

4.1.1-1

# Check if your issue is in the known issues list

Not listed as a known issue.

# OS/Distribution

Manjaro Linux 23.0.4

# Logs

`letsconnect-gui -d`
gives
```
2023-11-02 11:14:25,516 - MainThread - DEBUG - eduvpn.ui.app - app.py:70 - activate
2023/11/02 11:14:25 - Go - INFO - Previous configuration not found
2023-11-02 11:14:25,635 - <function ApplicationModelTransitions.get_previous_servers at 0x7f6984fc6fc0> - DEBUG - eduvpn.app - app.py:37 - Transition: NO_SERVER, old state: DEREGISTERED
2023-11-02 11:14:25,717 - <function ApplicationModelTransitions.parse_discovery at 0x7f6984fc7060> - DEBUG - eduvpn.app - app.py:44 - Transition: SEARCH_SERVER, old state: NO_SERVER
```
## Do you have a problem while adding before connecting?

Launching eduvpn from my start menu gives

![afbeelding](https://github.com/eduvpn/python-eduvpn-client/assets/11661087/2467d0c9-17fd-45c1-8f99-c8dfd62c4a24)

`eduvpn-cli -d` gives

![afbeelding](https://github.com/eduvpn/python-eduvpn-client/assets/11661087/a7d1f747-0be8-4566-96fe-da1deeaed2ac)

## Do you have a problem during or after connecting?

N/A

**Comment by HannoSpreeuw** [comment]
Thanks. I uninstalled via `yay -R python-eduvpn-client`.
`pip install "eduvpn-client[gui]"` works in both my conda base environment (Python 3.8) as well as in my conda py311 environment.

However, `eduvpn-gui` from my conda base environment gives
```
Traceback (most recent call last):
  File "/home/hanno/anaconda3/bin/eduvpn-gui", line 5, in <module>
    from eduvpn.ui.__main__ import eduvpn
  File "/home/hanno/anaconda3/lib/python3.8/site-packages/eduvpn/ui/__main__.py", line 5, in <module>
    import gi
  File "/home/hanno/anaconda3/lib/python3.8/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: /usr/lib/libgirepository-1.0.so.1: undefined symbol: g_string_free_and_steal
```
The same command from my conda py311 environment gives:
```
Traceback (most recent call last):
  File "/home/hanno/anaconda3/envs/py311/bin/eduvpn-gui", line 5, in <module>
    from eduvpn.ui.__main__ import eduvpn
  File "/home/hanno/anaconda3/envs/py311/lib/python3.11/site-packages/eduvpn/ui/__main__.py", line 13, in <module>
    from eduvpn.ui.app import EduVpnGtkApplication
  File "/home/hanno/anaconda3/envs/py311/lib/python3.11/site-packages/eduvpn/ui/app.py", line 12, in <module>
    from eduvpn import i18n, notify
  File "/home/hanno/anaconda3/envs/py311/lib/python3.11/site-packages/eduvpn/notify.py", line 3, in <module>
    gi.require_version("Notify", "0.7")  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hanno/anaconda3/envs/py311/lib/python3.11/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
```

**Comment by jwijenbergh** [comment]
Conda runs in a sort of virtual environment that hugely limits what types of libs you can load. E.g. you would also have to install glib inside of conda, conda install -c anaconda glib

I tried to get this working once but gave up

**Comment by HannoSpreeuw** [comment]
Okay.
System pip does not work either
```
which pip
--->
/usr/bin/pip
```
pip install "eduvpn-client[gui]" --user
---->
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

**Comment by jwijenbergh** [comment]
I'm not sure, this all works fine on default Debian/Ubuntu

You could also try pipx instead of pip like the error message says

**Comment by HannoSpreeuw** [comment]
Thanks for that, I never tried pipx.

`pipx install "eduvpn-client[gui]"`
gives 
```
  installed package eduvpn-client 4.1.3, installed using Python 3.11.5
  These apps are now globally available
    - eduvpn-cli
    - eduvpn-gui
    - letsconnect-cli
    - letsconnect-gui
done! ✨ 🌟 ✨
```

It does not give an eduvpn entry in my start menu, but `eduvpn-gui &` from bash works flawlessly.

**Comment by jwijenbergh** [comment]
Great! I will update the docs with this

**Comment by jwijenbergh** [comment]
Thanks @HannoSpreeuw this is now documented
