### ISSUE TITLE
Installation of GUI app on Ubuntu 22.04 fails

### ISSUE THREAD

**Issue by paulojraposo** [eduvpn/python-eduvpn-client#569]
# Installation

Via the Ubuntu 22.04 instructures [here](https://docs.eduvpn.org/client/linux/installation.html).

# Version

Unknown; `eduvpn-gui -v` results in errors. 4.2.1?

# OS/Distribution

Kubuntu 22.04

# Issue

Uninstalled the app (`sudo apt remove --purge eduvpn-client`). Then reinstalled (as explained above). Now, CLI app seems to work (though it has very little help messages when appending `-h`!). But the GUI is failing to launch with the following error messages:

```
$ eduvpn-gui 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (eduvpn-client 3.1.0 (/usr/lib/python3/dist-packages), Requirement.parse('eduvpn-client==4.2.1'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/eduvpn-gui", line 33, in <module>
    sys.exit(load_entry_point('eduvpn-client==4.2.1', 'gui_scripts', 'eduvpn-gui')())
  File "/usr/bin/eduvpn-gui", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/eduvpn/__init__.py", line 1, in <module>
    import pkg_resources
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3267, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3241, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 575, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 588, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'eduvpn-client==4.2.1' distribution was not found and is required by the application
```
Thanks!

**Comment by paulojraposo** [comment]
Actually, the CLI version doesn't work properly either. I try `eduvpn-cli interactive`, then enter either `61` or `996` (there are two entries for `University of Twente`!), and both give me errors as well. If it makes sense, I can open this as a different issue.

**Comment by jwijenbergh** [comment]
Closed due to inactivity

**Comment by paulojraposo** [comment]
Thanks, this seems to have fixed it. Didn't see the additional steps on the website when I was trying to reinstall it.

**Comment by jwijenbergh** [comment]
Great! Thanks for confirming
