### ISSUE TITLE
Broken client when a badly configured profile is used

### ISSUE THREAD

**Issue by Krafting** [eduvpn/python-eduvpn-client#615]
# Installation

How did you install the eduVPN/Let's Connect! client?

Fedora 41 - using the official repos 

# Version

What version of the client you are running? Try your package manager or otherwise `eduvpn-gui -v` or `letsconnect-gui -v`.

eduVPN GUI version: 4.4.0 with eduvpn-common version: 2.1.0

Double check that you are running the latest version, see [the releases page](https://github.com/eduvpn/python-eduvpn-client/releases) if a new version is available.

# Check if your issue is in the known issues list

The known issues list is available here: <https://docs.eduvpn.org/client/linux/support.html#known-issues>

Not on the Known issue page

# OS/Distribution

What operating system/distribution and version you are running?
Fedora 41 (Also happens in Ubuntu 22.04)

# Logs

## Do you have a problem while adding before connecting?

eduVPN/Let's Connect! will print out information to the console while running. Please try running `eduvpn-gui -d` or `eduvpn-cli -d` (or `letsconnect-cli -d`, `letsconnect-gui -d` for Let's Connect!) in a console. Note the `-d` flag here for verbose/debug logging. The log file is also located at `~/.config/eduvpn/log` for eduVPN and `~/.config/letsconnect/log` for Let's Connect!.

```
2024-11-28 11:35:31,513 - MainThread - DEBUG - eduvpn.ui.app - app.py:69 - activate
2024-11-28 11:35:31,593 - <function ApplicationModelTransitions.get_previous_servers at 0x7fdeec7587c0> - DEBUG - eduvpn.app - app.py:47 - Transition: MAIN, old state: 1
2024/11/28 11:35:31 - Go - DEBUG - got 304 for discovery, server_list.json not modified
2024-11-28 11:35:31,822 - MainThread - DEBUG - eduvpn.ui.ui - ui.py:1097 - server list refresh
2024-11-28 11:35:32,844 - MainThread - DEBUG - eduvpn.ui.ui - ui.py:1181 - on server row pressed
2024-11-28 11:35:32,919 - MainThread - DEBUG - eduvpn.ui.ui - ui.py:1142 - activated server: <eduvpn.server.Server object at 0x7fdeee0af890>
2024-11-28 11:35:32,921 - <function ApplicationModelTransitions.getting_config at 0x7fdeec758c20> - DEBUG - eduvpn.app - app.py:62 - Transition: GETTING_CONFIG, old state: 1
2024/11/28 11:35:33 - Go - DEBUG - i18n: could not load printer with tag: 'en' from map
2024/11/28 11:35:33 - Go - DEBUG - saving state file
2024/11/28 11:35:33 - Go - DEBUG - i18n: initializing languages...
2024-11-28 11:35:33,023 - <function ApplicationModelTransitions.get_previous_servers at 0x7fdeec7587c0> - DEBUG - eduvpn.app - app.py:47 - Transition: MAIN, old state: 4
2024-11-28 11:35:33,024 - call-model - ERROR - /usr/lib/python3.13/site-packages/eduvpn/utils.py - utils.py:143 - exception occurred: Failed to obtain a VPN configuration for server: 'https://eduvpn.univ-nantes.fr/'. The cause of the error is: failed obtaining HTTP resource: 'https://eduvpn.univ-nantes.fr/vpn-user-portal/api/v3/connect' as it gave an unsuccessful status code: '406'. Body: '{"error":"no common VPN protocol [CLIENT=openvpn+udp,openvpn+tcp,wireguard+udp,wireguard+tcp SERVER=None]"}'.
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/eduvpn/ui/ui.py", line 378, in call_model
    func(*(args))
    ~~~~^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/eduvpn/app.py", line 357, in connect
    config = self.connect_get_config(server, prefer_tcp=prefer_tcp)
  File "/usr/lib/python3.13/site-packages/eduvpn/app.py", line 272, in connect_get_config
    config = self.common.get_config(server.category_id, server.identifier, prefer_tcp)
  File "/usr/lib/python3.13/site-packages/eduvpn_common/main.py", line 257, in get_config
    forwardError(config_err)
    ~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/eduvpn_common/main.py", line 36, in forwardError
    raise WrappedError(d["message"], "en", d["misc"])
eduvpn_common.main.WrappedError: Failed to obtain a VPN configuration for server: 'https://eduvpn.univ-nantes.fr/'. The cause of the error is: failed obtaining HTTP resource: 'https://eduvpn.univ-nantes.fr/vpn-user-portal/api/v3/connect' as it gave an unsuccessful status code: '406'. Body: '{"error":"no common VPN protocol [CLIENT=openvpn+udp,openvpn+tcp,wireguard+udp,wireguard+tcp SERVER=None]"}'.
```

## Do you have a problem during or after connecting?

Problem when connecting:

After selecting a bad profile, I'm stuck in this page:

![image](https://github.com/user-attachments/assets/367a01d8-b0bd-4dc0-8e27-da82b82993a1)

Until I either fix the profile, or delete the configuration in `~/config/eduvpn/state.json`

Note that deleting the profile from the server still prevent the Client to connect to anything else.

**Comment by jwijenbergh** [comment]
sorry I forgot to reply. Do you mean that ideally it would be good that the client has an option on the main screen to switch profile? Maybe on "right click" on the server entry?

**Comment by Krafting** [comment]
> sorry I forgot to reply. Do you mean that ideally it would be good that the client has an option on the main screen to switch profile? Maybe on "right click" on the server entry?

No worries, ideally, if the app fails to load a profile, it should show the profile list again (with a user-friendly error message)

**Comment by jwijenbergh** [comment]
This repository was moved to Codeberg: https://codeberg.org/eduVPN/linux-app/issues/615
