### ISSUE TITLE
kill webserver thread on cancel in browser step better error parsing

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#74]
```
INFO:eduvpn.steps.browser:token dialog: cancel button pressed
 daarna wordt de locale http server niet gestopt
 en crasht de client als je erheen telnet
 ERROR:eduvpn.util:Can't obtain token: HTTPServer instance has no attribute 'path'
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/eduvpn/steps/browser.py", line 42, in <lambda>
    auth_url=auth_url, dialog=dialog, builder=builder))
  File "/usr/lib/python2.7/dist-packages/eduvpn/steps/browser.py", line 74, in _phase2_background
    code = get_oauth_token_code(port)
  File "/usr/lib/python2.7/dist-packages/eduvpn/oauth2.py", line 115, in get_oauth_token_code
    response = one_request(port)
  File "/usr/lib/python2.7/dist-packages/eduvpn/oauth2.py", line 85, in one_request
    parsed = urlparse(httpd.path)
AttributeError: HTTPServer instance has no attribute 'path'
```

**Comment by gijzelaerr** [comment]
@fkooman i've improved the error message, but stopping the webserver is not trivial since it is done on the main thread (non-gui thread). I could solve this by running the one request webserver in a different thread, but that requires a bit of work and i'm not really sure if it is worth that effort.

**Comment by fkooman** [comment]
you can stop the web server on OAuth response from the authorization server. In case of "cancel" this information is also provided to the redirect_uri endpoint.

**Comment by fkooman** [comment]
not sure what happens when user closes the web browser? is there feedback possible?

**Comment by gijzelaerr** [comment]
unfortunately, we can't find this out in a robust way. The user has to press the cancel button.

**Comment by gijzelaerr** [comment]
i've added a timeout of 2 minutes. if the timeout expires before getting a browser callback the port is closed. An error will be shown when the "opening your browser now" dialog is open, otherwise, it is only logged in the console.

The only point where this won't work properly is if a user gets to the "opening browser" screen, cancels, starts a new flow, gets to the "opening browser screen", previous requests timeouts. The user will then get an error, which is unrelated to the current enroll procedure.

I can't come up with something better, since it is impossible to figure out what is happening in the browser. So *or* we do this, *or* we roll this commit back and just keep that port open.
